// Code generated by ent, DO NOT EDIT.

package rechargeorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldAmount, v))
}

// ProviderOrderID applies equality check predicate on the "provider_order_id" field. It's identical to ProviderOrderIDEQ.
func ProviderOrderID(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldProviderOrderID, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaidAt, v))
}

// RefundedAmount applies equality check predicate on the "refunded_amount" field. It's identical to RefundedAmountEQ.
func RefundedAmount(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundedAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v Provider) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v Provider) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...Provider) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...Provider) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderOrderIDEQ applies the EQ predicate on the "provider_order_id" field.
func ProviderOrderIDEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldProviderOrderID, v))
}

// ProviderOrderIDNEQ applies the NEQ predicate on the "provider_order_id" field.
func ProviderOrderIDNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldProviderOrderID, v))
}

// ProviderOrderIDIn applies the In predicate on the "provider_order_id" field.
func ProviderOrderIDIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldProviderOrderID, vs...))
}

// ProviderOrderIDNotIn applies the NotIn predicate on the "provider_order_id" field.
func ProviderOrderIDNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldProviderOrderID, vs...))
}

// ProviderOrderIDGT applies the GT predicate on the "provider_order_id" field.
func ProviderOrderIDGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldProviderOrderID, v))
}

// ProviderOrderIDGTE applies the GTE predicate on the "provider_order_id" field.
func ProviderOrderIDGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldProviderOrderID, v))
}

// ProviderOrderIDLT applies the LT predicate on the "provider_order_id" field.
func ProviderOrderIDLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldProviderOrderID, v))
}

// ProviderOrderIDLTE applies the LTE predicate on the "provider_order_id" field.
func ProviderOrderIDLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldProviderOrderID, v))
}

// ProviderOrderIDContains applies the Contains predicate on the "provider_order_id" field.
func ProviderOrderIDContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldProviderOrderID, v))
}

// ProviderOrderIDHasPrefix applies the HasPrefix predicate on the "provider_order_id" field.
func ProviderOrderIDHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldProviderOrderID, v))
}

// ProviderOrderIDHasSuffix applies the HasSuffix predicate on the "provider_order_id" field.
func ProviderOrderIDHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldProviderOrderID, v))
}

// ProviderOrderIDIsNil applies the IsNil predicate on the "provider_order_id" field.
func ProviderOrderIDIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldProviderOrderID))
}

// ProviderOrderIDNotNil applies the NotNil predicate on the "provider_order_id" field.
func ProviderOrderIDNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldProviderOrderID))
}

// ProviderOrderIDEqualFold applies the EqualFold predicate on the "provider_order_id" field.
func ProviderOrderIDEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldProviderOrderID, v))
}

// ProviderOrderIDContainsFold applies the ContainsFold predicate on the "provider_order_id" field.
func ProviderOrderIDContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldProviderOrderID, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldPaidAt))
}

// RefundedAmountEQ applies the EQ predicate on the "refunded_amount" field.
func RefundedAmountEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundedAmount, v))
}

// RefundedAmountNEQ applies the NEQ predicate on the "refunded_amount" field.
func RefundedAmountNEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldRefundedAmount, v))
}

// RefundedAmountIn applies the In predicate on the "refunded_amount" field.
func RefundedAmountIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldRefundedAmount, vs...))
}

// RefundedAmountNotIn applies the NotIn predicate on the "refunded_amount" field.
func RefundedAmountNotIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldRefundedAmount, vs...))
}

// RefundedAmountGT applies the GT predicate on the "refunded_amount" field.
func RefundedAmountGT(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldRefundedAmount, v))
}

// RefundedAmountGTE applies the GTE predicate on the "refunded_amount" field.
func RefundedAmountGTE(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldRefundedAmount, v))
}

// RefundedAmountLT applies the LT predicate on the "refunded_amount" field.
func RefundedAmountLT(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldRefundedAmount, v))
}

// RefundedAmountLTE applies the LTE predicate on the "refunded_amount" field.
func RefundedAmountLTE(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldRefundedAmount, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RechargeOrder {
	return predicate.RechargeOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RechargeOrder {
	return predicate.RechargeOrder(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RechargeOrder) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RechargeOrder) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RechargeOrder) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.NotPredicates(p))
}
