// Package mockdata generates deterministic, safe mock data for development and
// test environments. It must never be pointed at a production database.
package mockdata

import (
	"context"
	"fmt"
	"math/rand"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/school-api/school-api-v1/ent"
	"github.com/school-api/school-api-v1/ent/adminuser"
	"github.com/school-api/school-api-v1/ent/department"
	"github.com/school-api/school-api-v1/ent/group"
	"github.com/school-api/school-api-v1/ent/user"
	"github.com/school-api/school-api-v1/ent/usertoken"
	"github.com/school-api/school-api-v1/internal/auth"
	"github.com/school-api/school-api-v1/internal/repository"
	"github.com/school-api/school-api-v1/internal/service"
)

// Prefix is used to tag all mock entities so they can be identified and cleaned
// up without affecting user-created data.
const Prefix = "mockgen"

// Generator creates mock data for the completed Phase 3 entities. All created
// records carry the Prefix tag in their identifying fields.
type Generator struct {
	client *ent.Client
	seed   int64
	rnd    *rand.Rand
}

// NewGenerator creates a Generator. The seed makes generated values deterministic
// when the same seed is reused, which is useful for reproducible test fixtures.
func NewGenerator(client *ent.Client, seed int64) *Generator {
	return &Generator{
		client: client,
		seed:   seed,
		rnd:    rand.New(rand.NewSource(seed)),
	}
}

// GeneratedToken records a plaintext API key together with its metadata.
type GeneratedToken struct {
	UserID    uuid.UUID
	TokenID   uuid.UUID
	Name      string
	Plaintext string
}

// GeneratedSet holds all entities created in one generation run.
type GeneratedSet struct {
	Admin       *ent.AdminUser
	Groups      []*ent.Group
	Departments []*ent.Department
	Users       []*ent.User
	Tokens      []GeneratedToken
}

// CreateAdmin creates a single tagged admin user.
func (g *Generator) CreateAdmin(ctx context.Context, username, password string, role adminuser.Role) (*ent.AdminUser, error) {
	hash, err := auth.HashPassword(auth.DefaultBcryptCost, password)
	if err != nil {
		return nil, fmt.Errorf("hash admin password: %w", err)
	}

	admin, err := repository.NewEntAdminRepository(g.client).
		CreateAdmin(ctx, username, hash, role)
	if err != nil {
		return nil, fmt.Errorf("create admin %q: %w", username, err)
	}
	return admin, nil
}

// CreateGroups creates a number of tagged groups.
func (g *Generator) CreateGroups(ctx context.Context, count int) ([]*ent.Group, error) {
	groups := make([]*ent.Group, 0, count)
	for i := 0; i < count; i++ {
		gr, err := g.client.Group.Create().
			SetName(fmt.Sprintf("%s Group %03d", title(Prefix), i+1)).
			SetCode(fmt.Sprintf("%s-group-%s", Prefix, g.suffix())).
			SetDescription("Auto-generated by mockgen for development/testing only.").
			SetSortOrder(i).
			SetStatus(group.StatusActive).
			Save(ctx)
		if err != nil {
			return nil, fmt.Errorf("create group %d: %w", i, err)
		}
		groups = append(groups, gr)
	}
	return groups, nil
}

// CreateDepartments creates a shallow department tree: rootCount root
// departments, each with childrenPerRoot direct children. Use a repository so
// level and path are maintained consistently with production code.
func (g *Generator) CreateDepartments(ctx context.Context, rootCount, childrenPerRoot int) ([]*ent.Department, error) {
	repo := repository.NewEntDepartmentRepository(g.client)
	deps := make([]*ent.Department, 0, rootCount*(childrenPerRoot+1))

	for i := 0; i < rootCount; i++ {
		root, err := repo.Create(ctx, repository.CreateDepartmentInput{
			Name:      fmt.Sprintf("%s Root Dept %03d", title(Prefix), i+1),
			Code:      fmt.Sprintf("%s-root-%s", Prefix, g.suffix()),
			SortOrder: i,
			Status:    department.StatusActive,
		})
		if err != nil {
			return nil, fmt.Errorf("create root department %d: %w", i, err)
		}
		deps = append(deps, root)

		for j := 0; j < childrenPerRoot; j++ {
			child, err := repo.Create(ctx, repository.CreateDepartmentInput{
				Name:      fmt.Sprintf("%s Child Dept %03d-%03d", title(Prefix), i+1, j+1),
				Code:      fmt.Sprintf("%s-child-%s", Prefix, g.suffix()),
				ParentID:  &root.ID,
				SortOrder: j,
				Status:    department.StatusActive,
			})
			if err != nil {
				return nil, fmt.Errorf("create child department %d-%d: %w", i, j, err)
			}
			deps = append(deps, child)
		}
	}
	return deps, nil
}

// CreateUsers creates count users, randomly assigning a group and department from
// the provided slices when available.
func (g *Generator) CreateUsers(ctx context.Context, count int, groups []*ent.Group, departments []*ent.Department) ([]*ent.User, error) {
	svc := service.NewUserService(repository.NewEntUserRepository(g.client), auth.DefaultBcryptCost)
	users := make([]*ent.User, 0, count)

	for i := 0; i < count; i++ {
		username := fmt.Sprintf("%s-user-%s", Prefix, g.suffix())
		input := service.CreateUserInput{
			Username: username,
			Password: defaultPassword(),
			Name:     fmt.Sprintf("%s User %03d", title(Prefix), i+1),
			Email:    fmt.Sprintf("%s@example.com", username),
			Phone:    fmt.Sprintf("138%08d", g.rnd.Intn(100000000)),
			Role:     randomRole(g.rnd),
			Gender:   randomGender(g.rnd),
			Status:   user.StatusActive,
		}
		if len(groups) > 0 {
			g := groups[g.rnd.Intn(len(groups))]
			input.GroupID = &g.ID
		}
		if len(departments) > 0 {
			d := departments[g.rnd.Intn(len(departments))]
			input.DepartmentID = &d.ID
		}

		resp, err := svc.CreateUser(ctx, input)
		if err != nil {
			return nil, fmt.Errorf("create user %d: %w", i, err)
		}

		u, err := g.client.User.Get(ctx, uuid.MustParse(resp.ID))
		if err != nil {
			return nil, fmt.Errorf("fetch created user %d: %w", i, err)
		}
		users = append(users, u)
	}
	return users, nil
}

// CreateTokens creates tokensPerUser API tokens for every supplied user.
func (g *Generator) CreateTokens(ctx context.Context, tokensPerUser int, users []*ent.User) ([]GeneratedToken, error) {
	svc := service.NewUserTokenService(
		repository.NewEntUserTokenRepository(g.client),
		repository.NewEntUserRepository(g.client),
		nil, // mock tokens do not need retrievable ciphertext
		nil, // no default quota for mock data
	)
	tokens := make([]GeneratedToken, 0, len(users)*tokensPerUser)

	for _, u := range users {
		for j := 0; j < tokensPerUser; j++ {
			input := service.CreateUserTokenInput{
				UserID: u.ID,
				Name:   fmt.Sprintf("%s-token-%03d", Prefix, j+1),
			}
			resp, plaintext, err := svc.CreateUserToken(ctx, input)
			if err != nil {
				return nil, fmt.Errorf("create token for user %s: %w", u.ID, err)
			}
			tokens = append(tokens, GeneratedToken{
				UserID:    u.ID,
				TokenID:   uuid.MustParse(resp.ID),
				Name:      resp.Name,
				Plaintext: plaintext,
			})
		}
	}
	return tokens, nil
}

// Generate runs the full scenario and returns all created entities.
func (g *Generator) Generate(ctx context.Context, cfg ScenarioConfig) (*GeneratedSet, error) {
	set := &GeneratedSet{}

	admin, err := g.CreateAdmin(ctx, cfg.AdminUsername, cfg.AdminPassword, cfg.AdminRole)
	if err != nil {
		return nil, fmt.Errorf("generate admin: %w", err)
	}
	set.Admin = admin

	groups, err := g.CreateGroups(ctx, cfg.GroupCount)
	if err != nil {
		return nil, fmt.Errorf("generate groups: %w", err)
	}
	set.Groups = groups

	departments, err := g.CreateDepartments(ctx, cfg.RootDepartmentCount, cfg.ChildrenPerRoot)
	if err != nil {
		return nil, fmt.Errorf("generate departments: %w", err)
	}
	set.Departments = departments

	users, err := g.CreateUsers(ctx, cfg.UserCount, groups, departments)
	if err != nil {
		return nil, fmt.Errorf("generate users: %w", err)
	}
	set.Users = users

	if cfg.TokensPerUser > 0 {
		tokens, err := g.CreateTokens(ctx, cfg.TokensPerUser, users)
		if err != nil {
			return nil, fmt.Errorf("generate tokens: %w", err)
		}
		set.Tokens = tokens
	}

	return set, nil
}

// Cleanup removes all records tagged with the mockgen prefix. It deletes in an
// order that respects foreign key constraints.
func (g *Generator) Cleanup(ctx context.Context) error {
	// User tokens -> users -> departments -> groups -> admin.
	if _, err := g.client.UserToken.Delete().Where(usertoken.NameHasPrefix(Prefix)).Exec(ctx); err != nil {
		return fmt.Errorf("cleanup user tokens: %w", err)
	}
	if _, err := g.client.User.Delete().Where(user.UsernameHasPrefix(Prefix)).Exec(ctx); err != nil {
		return fmt.Errorf("cleanup users: %w", err)
	}
	if _, err := g.client.Department.Delete().Where(department.CodeHasPrefix(Prefix)).Exec(ctx); err != nil {
		return fmt.Errorf("cleanup departments: %w", err)
	}
	if _, err := g.client.Group.Delete().Where(group.CodeHasPrefix(Prefix)).Exec(ctx); err != nil {
		return fmt.Errorf("cleanup groups: %w", err)
	}
	if _, err := g.client.AdminUser.Delete().Where(adminuser.UsernameHasPrefix(Prefix)).Exec(ctx); err != nil {
		return fmt.Errorf("cleanup admin users: %w", err)
	}
	return nil
}

// ScenarioConfig controls the volume of mock data generated by Generate.
type ScenarioConfig struct {
	AdminUsername       string
	AdminPassword       string
	AdminRole           adminuser.Role
	GroupCount          int
	RootDepartmentCount int
	ChildrenPerRoot     int
	UserCount           int
	TokensPerUser       int
}

// DefaultScenario returns a small, deterministic scenario suitable for local
// development smoke tests.
func DefaultScenario() ScenarioConfig {
	return ScenarioConfig{
		AdminUsername:       "mockgen-admin",
		AdminPassword:       "MockGen@123",
		AdminRole:           adminuser.RoleAdmin,
		GroupCount:          2,
		RootDepartmentCount: 2,
		ChildrenPerRoot:     2,
		UserCount:           5,
		TokensPerUser:       2,
	}
}

func (g *Generator) suffix() string {
	return uuid.NewString()[:8]
}

func title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func defaultPassword() string {
	return "MockGen@123"
}

func randomRole(r *rand.Rand) user.Role {
	roles := []user.Role{user.RoleStudent, user.RoleTeacher, user.RoleStaff}
	return roles[r.Intn(len(roles))]
}

func randomGender(r *rand.Rand) string {
	genders := []string{"male", "female", "unknown"}
	return genders[r.Intn(len(genders))]
}

// MustBeNonProduction returns an error if env indicates a production deployment.
// Use it in any CLI or script entrypoint before opening a database connection.
func MustBeNonProduction(env string) error {
	env = strings.ToLower(strings.TrimSpace(env))
	if env == "production" || env == "prod" {
		return fmt.Errorf("refusing to generate mock data in environment %q", env)
	}
	return nil
}

// DefaultSeed is a fixed seed that produces a reproducible dataset.
const DefaultSeed int64 = 20260901

// QuotaLimitExample is an example quota limit that can be assigned to generated
// tokens when the caller chooses to set one.
func QuotaLimitExample() int64 {
	return 10000
}

// FutureExpiry returns a fixed future expiry time for generated tokens.
func FutureExpiry() time.Time {
	return time.Now().UTC().Add(30 * 24 * time.Hour)
}
