// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/account"
	"github.com/school-api/school-api-v1/ent/calllog"
	"github.com/school-api/school-api-v1/ent/platform"
	"github.com/school-api/school-api-v1/ent/predicate"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpdate) SetUpdatedAt(v time.Time) *AccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *AccountUpdate) SetPlatformID(v uuid.UUID) *AccountUpdate {
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillablePlatformID(v *uuid.UUID) *AccountUpdate {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdate) SetName(v string) *AccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableName(v *string) *AccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_u *AccountUpdate) SetAPIKeyEncrypted(v string) *AccountUpdate {
	_u.mutation.SetAPIKeyEncrypted(v)
	return _u
}

// SetNillableAPIKeyEncrypted sets the "api_key_encrypted" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAPIKeyEncrypted(v *string) *AccountUpdate {
	if v != nil {
		_u.SetAPIKeyEncrypted(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *AccountUpdate) SetWeight(v int) *AccountUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableWeight(v *int) *AccountUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *AccountUpdate) AddWeight(v int) *AccountUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetMaxRpm sets the "max_rpm" field.
func (_u *AccountUpdate) SetMaxRpm(v int) *AccountUpdate {
	_u.mutation.ResetMaxRpm()
	_u.mutation.SetMaxRpm(v)
	return _u
}

// SetNillableMaxRpm sets the "max_rpm" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableMaxRpm(v *int) *AccountUpdate {
	if v != nil {
		_u.SetMaxRpm(*v)
	}
	return _u
}

// AddMaxRpm adds value to the "max_rpm" field.
func (_u *AccountUpdate) AddMaxRpm(v int) *AccountUpdate {
	_u.mutation.AddMaxRpm(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountUpdate) SetStatus(v account.Status) *AccountUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableStatus(v *account.Status) *AccountUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorCount sets the "error_count" field.
func (_u *AccountUpdate) SetErrorCount(v int) *AccountUpdate {
	_u.mutation.ResetErrorCount()
	_u.mutation.SetErrorCount(v)
	return _u
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableErrorCount(v *int) *AccountUpdate {
	if v != nil {
		_u.SetErrorCount(*v)
	}
	return _u
}

// AddErrorCount adds value to the "error_count" field.
func (_u *AccountUpdate) AddErrorCount(v int) *AccountUpdate {
	_u.mutation.AddErrorCount(v)
	return _u
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (_u *AccountUpdate) SetPlatform(v *Platform) *AccountUpdate {
	return _u.SetPlatformID(v.ID)
}

// AddCallLogIDs adds the "call_logs" edge to the CallLog entity by IDs.
func (_u *AccountUpdate) AddCallLogIDs(ids ...uuid.UUID) *AccountUpdate {
	_u.mutation.AddCallLogIDs(ids...)
	return _u
}

// AddCallLogs adds the "call_logs" edges to the CallLog entity.
func (_u *AccountUpdate) AddCallLogs(v ...*CallLog) *AccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCallLogIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearPlatform clears the "platform" edge to the Platform entity.
func (_u *AccountUpdate) ClearPlatform() *AccountUpdate {
	_u.mutation.ClearPlatform()
	return _u
}

// ClearCallLogs clears all "call_logs" edges to the CallLog entity.
func (_u *AccountUpdate) ClearCallLogs() *AccountUpdate {
	_u.mutation.ClearCallLogs()
	return _u
}

// RemoveCallLogIDs removes the "call_logs" edge to CallLog entities by IDs.
func (_u *AccountUpdate) RemoveCallLogIDs(ids ...uuid.UUID) *AccountUpdate {
	_u.mutation.RemoveCallLogIDs(ids...)
	return _u
}

// RemoveCallLogs removes "call_logs" edges to CallLog entities.
func (_u *AccountUpdate) RemoveCallLogs(v ...*CallLog) *AccountUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCallLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyEncrypted(); ok {
		if err := account.APIKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "api_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "Account.api_key_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := account.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Account.status": %w`, err)}
		}
	}
	if _u.mutation.PlatformCleared() && len(_u.mutation.PlatformIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.platform"`)
	}
	return nil
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(account.FieldAPIKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(account.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(account.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxRpm(); ok {
		_spec.SetField(account.FieldMaxRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRpm(); ok {
		_spec.AddField(account.FieldMaxRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(account.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorCount(); ok {
		_spec.SetField(account.FieldErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedErrorCount(); ok {
		_spec.AddField(account.FieldErrorCount, field.TypeInt, value)
	}
	if _u.mutation.PlatformCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.PlatformTable,
			Columns: []string{account.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platform.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.PlatformTable,
			Columns: []string{account.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platform.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CallLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.CallLogsTable,
			Columns: []string{account.CallLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calllog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCallLogsIDs(); len(nodes) > 0 && !_u.mutation.CallLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.CallLogsTable,
			Columns: []string{account.CallLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calllog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CallLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.CallLogsTable,
			Columns: []string{account.CallLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calllog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpdateOne) SetUpdatedAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *AccountUpdateOne) SetPlatformID(v uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillablePlatformID(v *uuid.UUID) *AccountUpdateOne {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdateOne) SetName(v string) *AccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableName(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_u *AccountUpdateOne) SetAPIKeyEncrypted(v string) *AccountUpdateOne {
	_u.mutation.SetAPIKeyEncrypted(v)
	return _u
}

// SetNillableAPIKeyEncrypted sets the "api_key_encrypted" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAPIKeyEncrypted(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetAPIKeyEncrypted(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *AccountUpdateOne) SetWeight(v int) *AccountUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableWeight(v *int) *AccountUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *AccountUpdateOne) AddWeight(v int) *AccountUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetMaxRpm sets the "max_rpm" field.
func (_u *AccountUpdateOne) SetMaxRpm(v int) *AccountUpdateOne {
	_u.mutation.ResetMaxRpm()
	_u.mutation.SetMaxRpm(v)
	return _u
}

// SetNillableMaxRpm sets the "max_rpm" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableMaxRpm(v *int) *AccountUpdateOne {
	if v != nil {
		_u.SetMaxRpm(*v)
	}
	return _u
}

// AddMaxRpm adds value to the "max_rpm" field.
func (_u *AccountUpdateOne) AddMaxRpm(v int) *AccountUpdateOne {
	_u.mutation.AddMaxRpm(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountUpdateOne) SetStatus(v account.Status) *AccountUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableStatus(v *account.Status) *AccountUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorCount sets the "error_count" field.
func (_u *AccountUpdateOne) SetErrorCount(v int) *AccountUpdateOne {
	_u.mutation.ResetErrorCount()
	_u.mutation.SetErrorCount(v)
	return _u
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableErrorCount(v *int) *AccountUpdateOne {
	if v != nil {
		_u.SetErrorCount(*v)
	}
	return _u
}

// AddErrorCount adds value to the "error_count" field.
func (_u *AccountUpdateOne) AddErrorCount(v int) *AccountUpdateOne {
	_u.mutation.AddErrorCount(v)
	return _u
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (_u *AccountUpdateOne) SetPlatform(v *Platform) *AccountUpdateOne {
	return _u.SetPlatformID(v.ID)
}

// AddCallLogIDs adds the "call_logs" edge to the CallLog entity by IDs.
func (_u *AccountUpdateOne) AddCallLogIDs(ids ...uuid.UUID) *AccountUpdateOne {
	_u.mutation.AddCallLogIDs(ids...)
	return _u
}

// AddCallLogs adds the "call_logs" edges to the CallLog entity.
func (_u *AccountUpdateOne) AddCallLogs(v ...*CallLog) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCallLogIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearPlatform clears the "platform" edge to the Platform entity.
func (_u *AccountUpdateOne) ClearPlatform() *AccountUpdateOne {
	_u.mutation.ClearPlatform()
	return _u
}

// ClearCallLogs clears all "call_logs" edges to the CallLog entity.
func (_u *AccountUpdateOne) ClearCallLogs() *AccountUpdateOne {
	_u.mutation.ClearCallLogs()
	return _u
}

// RemoveCallLogIDs removes the "call_logs" edge to CallLog entities by IDs.
func (_u *AccountUpdateOne) RemoveCallLogIDs(ids ...uuid.UUID) *AccountUpdateOne {
	_u.mutation.RemoveCallLogIDs(ids...)
	return _u
}

// RemoveCallLogs removes "call_logs" edges to CallLog entities.
func (_u *AccountUpdateOne) RemoveCallLogs(v ...*CallLog) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCallLogIDs(ids...)
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyEncrypted(); ok {
		if err := account.APIKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "api_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "Account.api_key_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := account.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Account.status": %w`, err)}
		}
	}
	if _u.mutation.PlatformCleared() && len(_u.mutation.PlatformIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.platform"`)
	}
	return nil
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(account.FieldAPIKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(account.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(account.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxRpm(); ok {
		_spec.SetField(account.FieldMaxRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRpm(); ok {
		_spec.AddField(account.FieldMaxRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(account.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorCount(); ok {
		_spec.SetField(account.FieldErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedErrorCount(); ok {
		_spec.AddField(account.FieldErrorCount, field.TypeInt, value)
	}
	if _u.mutation.PlatformCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.PlatformTable,
			Columns: []string{account.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platform.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.PlatformTable,
			Columns: []string{account.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platform.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CallLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.CallLogsTable,
			Columns: []string{account.CallLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calllog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCallLogsIDs(); len(nodes) > 0 && !_u.mutation.CallLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.CallLogsTable,
			Columns: []string{account.CallLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calllog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CallLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.CallLogsTable,
			Columns: []string{account.CallLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calllog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
