// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/school-api/school-api-v1/ent/aimodel"
	"github.com/school-api/school-api-v1/ent/predicate"
)

// AIModelUpdate is the builder for updating AIModel entities.
type AIModelUpdate struct {
	config
	hooks    []Hook
	mutation *AIModelMutation
}

// Where appends a list predicates to the AIModelUpdate builder.
func (_u *AIModelUpdate) Where(ps ...predicate.AIModel) *AIModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIModelUpdate) SetUpdatedAt(v time.Time) *AIModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AIModelUpdate) SetName(v string) *AIModelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableName(v *string) *AIModelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUpstreamName sets the "upstream_name" field.
func (_u *AIModelUpdate) SetUpstreamName(v string) *AIModelUpdate {
	_u.mutation.SetUpstreamName(v)
	return _u
}

// SetNillableUpstreamName sets the "upstream_name" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableUpstreamName(v *string) *AIModelUpdate {
	if v != nil {
		_u.SetUpstreamName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AIModelUpdate) SetType(v aimodel.Type) *AIModelUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableType(v *aimodel.Type) *AIModelUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *AIModelUpdate) SetInputPrice(v int64) *AIModelUpdate {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableInputPrice(v *int64) *AIModelUpdate {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *AIModelUpdate) AddInputPrice(v int64) *AIModelUpdate {
	_u.mutation.AddInputPrice(v)
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *AIModelUpdate) SetOutputPrice(v int64) *AIModelUpdate {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableOutputPrice(v *int64) *AIModelUpdate {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *AIModelUpdate) AddOutputPrice(v int64) *AIModelUpdate {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *AIModelUpdate) SetIsEnabled(v bool) *AIModelUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableIsEnabled(v *bool) *AIModelUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// Mutation returns the AIModelMutation object of the builder.
func (_u *AIModelUpdate) Mutation() *AIModelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AIModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AIModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aimodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIModelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := aimodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AIModel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamName(); ok {
		if err := aimodel.UpstreamNameValidator(v); err != nil {
			return &ValidationError{Name: "upstream_name", err: fmt.Errorf(`ent: validator failed for field "AIModel.upstream_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := aimodel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AIModel.type": %w`, err)}
		}
	}
	return nil
}

func (_u *AIModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aimodel.Table, aimodel.Columns, sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aimodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aimodel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamName(); ok {
		_spec.SetField(aimodel.FieldUpstreamName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(aimodel.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(aimodel.FieldInputPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(aimodel.FieldInputPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(aimodel.FieldOutputPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(aimodel.FieldOutputPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(aimodel.FieldIsEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aimodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AIModelUpdateOne is the builder for updating a single AIModel entity.
type AIModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AIModelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIModelUpdateOne) SetUpdatedAt(v time.Time) *AIModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AIModelUpdateOne) SetName(v string) *AIModelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableName(v *string) *AIModelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUpstreamName sets the "upstream_name" field.
func (_u *AIModelUpdateOne) SetUpstreamName(v string) *AIModelUpdateOne {
	_u.mutation.SetUpstreamName(v)
	return _u
}

// SetNillableUpstreamName sets the "upstream_name" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableUpstreamName(v *string) *AIModelUpdateOne {
	if v != nil {
		_u.SetUpstreamName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AIModelUpdateOne) SetType(v aimodel.Type) *AIModelUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableType(v *aimodel.Type) *AIModelUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *AIModelUpdateOne) SetInputPrice(v int64) *AIModelUpdateOne {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableInputPrice(v *int64) *AIModelUpdateOne {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *AIModelUpdateOne) AddInputPrice(v int64) *AIModelUpdateOne {
	_u.mutation.AddInputPrice(v)
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *AIModelUpdateOne) SetOutputPrice(v int64) *AIModelUpdateOne {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableOutputPrice(v *int64) *AIModelUpdateOne {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *AIModelUpdateOne) AddOutputPrice(v int64) *AIModelUpdateOne {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *AIModelUpdateOne) SetIsEnabled(v bool) *AIModelUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableIsEnabled(v *bool) *AIModelUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// Mutation returns the AIModelMutation object of the builder.
func (_u *AIModelUpdateOne) Mutation() *AIModelMutation {
	return _u.mutation
}

// Where appends a list predicates to the AIModelUpdate builder.
func (_u *AIModelUpdateOne) Where(ps ...predicate.AIModel) *AIModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AIModelUpdateOne) Select(field string, fields ...string) *AIModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AIModel entity.
func (_u *AIModelUpdateOne) Save(ctx context.Context) (*AIModel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIModelUpdateOne) SaveX(ctx context.Context) *AIModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AIModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aimodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIModelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := aimodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AIModel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamName(); ok {
		if err := aimodel.UpstreamNameValidator(v); err != nil {
			return &ValidationError{Name: "upstream_name", err: fmt.Errorf(`ent: validator failed for field "AIModel.upstream_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := aimodel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AIModel.type": %w`, err)}
		}
	}
	return nil
}

func (_u *AIModelUpdateOne) sqlSave(ctx context.Context) (_node *AIModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aimodel.Table, aimodel.Columns, sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AIModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aimodel.FieldID)
		for _, f := range fields {
			if !aimodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aimodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aimodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aimodel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamName(); ok {
		_spec.SetField(aimodel.FieldUpstreamName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(aimodel.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(aimodel.FieldInputPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(aimodel.FieldInputPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(aimodel.FieldOutputPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(aimodel.FieldOutputPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(aimodel.FieldIsEnabled, field.TypeBool, value)
	}
	_node = &AIModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aimodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
