// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/account"
	"github.com/school-api/school-api-v1/ent/adminuser"
	"github.com/school-api/school-api-v1/ent/alertrecord"
	"github.com/school-api/school-api-v1/ent/alertrule"
	"github.com/school-api/school-api-v1/ent/user"
	"github.com/school-api/school-api-v1/ent/usertoken"
)

// AlertRecord is the model entity for the AlertRecord schema.
type AlertRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RuleID holds the value of the "rule_id" field.
	RuleID *uuid.UUID `json:"rule_id,omitempty"`
	// Metric holds the value of the "metric" field.
	Metric string `json:"metric,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *uuid.UUID `json:"user_id,omitempty"`
	// TokenID holds the value of the "token_id" field.
	TokenID *uuid.UUID `json:"token_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *uuid.UUID `json:"account_id,omitempty"`
	// TriggeredValue holds the value of the "triggered_value" field.
	TriggeredValue int64 `json:"triggered_value,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// IsResolved holds the value of the "is_resolved" field.
	IsResolved bool `json:"is_resolved,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// ResolvedBy holds the value of the "resolved_by" field.
	ResolvedBy *uuid.UUID `json:"resolved_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AlertRecordQuery when eager-loading is set.
	Edges        AlertRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AlertRecordEdges holds the relations/edges for other nodes in the graph.
type AlertRecordEdges struct {
	// Rule holds the value of the rule edge.
	Rule *AlertRule `json:"rule,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Token holds the value of the token edge.
	Token *UserToken `json:"token,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Resolver holds the value of the resolver edge.
	Resolver *AdminUser `json:"resolver,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// RuleOrErr returns the Rule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertRecordEdges) RuleOrErr() (*AlertRule, error) {
	if e.Rule != nil {
		return e.Rule, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: alertrule.Label}
	}
	return nil, &NotLoadedError{edge: "rule"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TokenOrErr returns the Token value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertRecordEdges) TokenOrErr() (*UserToken, error) {
	if e.Token != nil {
		return e.Token, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: usertoken.Label}
	}
	return nil, &NotLoadedError{edge: "token"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertRecordEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// ResolverOrErr returns the Resolver value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertRecordEdges) ResolverOrErr() (*AdminUser, error) {
	if e.Resolver != nil {
		return e.Resolver, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: adminuser.Label}
	}
	return nil, &NotLoadedError{edge: "resolver"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AlertRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alertrecord.FieldRuleID, alertrecord.FieldUserID, alertrecord.FieldTokenID, alertrecord.FieldAccountID, alertrecord.FieldResolvedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case alertrecord.FieldIsResolved:
			values[i] = new(sql.NullBool)
		case alertrecord.FieldTriggeredValue:
			values[i] = new(sql.NullInt64)
		case alertrecord.FieldMetric, alertrecord.FieldMessage:
			values[i] = new(sql.NullString)
		case alertrecord.FieldCreatedAt, alertrecord.FieldUpdatedAt, alertrecord.FieldResolvedAt:
			values[i] = new(sql.NullTime)
		case alertrecord.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AlertRecord fields.
func (_m *AlertRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alertrecord.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case alertrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case alertrecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case alertrecord.FieldRuleID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				_m.RuleID = new(uuid.UUID)
				*_m.RuleID = *value.S.(*uuid.UUID)
			}
		case alertrecord.FieldMetric:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metric", values[i])
			} else if value.Valid {
				_m.Metric = value.String
			}
		case alertrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uuid.UUID)
				*_m.UserID = *value.S.(*uuid.UUID)
			}
		case alertrecord.FieldTokenID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field token_id", values[i])
			} else if value.Valid {
				_m.TokenID = new(uuid.UUID)
				*_m.TokenID = *value.S.(*uuid.UUID)
			}
		case alertrecord.FieldAccountID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(uuid.UUID)
				*_m.AccountID = *value.S.(*uuid.UUID)
			}
		case alertrecord.FieldTriggeredValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_value", values[i])
			} else if value.Valid {
				_m.TriggeredValue = value.Int64
			}
		case alertrecord.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case alertrecord.FieldIsResolved:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_resolved", values[i])
			} else if value.Valid {
				_m.IsResolved = value.Bool
			}
		case alertrecord.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		case alertrecord.FieldResolvedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_by", values[i])
			} else if value.Valid {
				_m.ResolvedBy = new(uuid.UUID)
				*_m.ResolvedBy = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AlertRecord.
// This includes values selected through modifiers, order, etc.
func (_m *AlertRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRule queries the "rule" edge of the AlertRecord entity.
func (_m *AlertRecord) QueryRule() *AlertRuleQuery {
	return NewAlertRecordClient(_m.config).QueryRule(_m)
}

// QueryUser queries the "user" edge of the AlertRecord entity.
func (_m *AlertRecord) QueryUser() *UserQuery {
	return NewAlertRecordClient(_m.config).QueryUser(_m)
}

// QueryToken queries the "token" edge of the AlertRecord entity.
func (_m *AlertRecord) QueryToken() *UserTokenQuery {
	return NewAlertRecordClient(_m.config).QueryToken(_m)
}

// QueryAccount queries the "account" edge of the AlertRecord entity.
func (_m *AlertRecord) QueryAccount() *AccountQuery {
	return NewAlertRecordClient(_m.config).QueryAccount(_m)
}

// QueryResolver queries the "resolver" edge of the AlertRecord entity.
func (_m *AlertRecord) QueryResolver() *AdminUserQuery {
	return NewAlertRecordClient(_m.config).QueryResolver(_m)
}

// Update returns a builder for updating this AlertRecord.
// Note that you need to call AlertRecord.Unwrap() before calling this method if this AlertRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AlertRecord) Update() *AlertRecordUpdateOne {
	return NewAlertRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AlertRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AlertRecord) Unwrap() *AlertRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AlertRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AlertRecord) String() string {
	var builder strings.Builder
	builder.WriteString("AlertRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RuleID; v != nil {
		builder.WriteString("rule_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("metric=")
	builder.WriteString(_m.Metric)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TokenID; v != nil {
		builder.WriteString("token_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("triggered_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggeredValue))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("is_resolved=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsResolved))
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResolvedBy; v != nil {
		builder.WriteString("resolved_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AlertRecords is a parsable slice of AlertRecord.
type AlertRecords []*AlertRecord
