// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/school-api/school-api-v1/ent/alertrule"
	"github.com/school-api/school-api-v1/ent/predicate"
)

// AlertRuleUpdate is the builder for updating AlertRule entities.
type AlertRuleUpdate struct {
	config
	hooks    []Hook
	mutation *AlertRuleMutation
}

// Where appends a list predicates to the AlertRuleUpdate builder.
func (_u *AlertRuleUpdate) Where(ps ...predicate.AlertRule) *AlertRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlertRuleUpdate) SetUpdatedAt(v time.Time) *AlertRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AlertRuleUpdate) SetName(v string) *AlertRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AlertRuleUpdate) SetNillableName(v *string) *AlertRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMetric sets the "metric" field.
func (_u *AlertRuleUpdate) SetMetric(v alertrule.Metric) *AlertRuleUpdate {
	_u.mutation.SetMetric(v)
	return _u
}

// SetNillableMetric sets the "metric" field if the given value is not nil.
func (_u *AlertRuleUpdate) SetNillableMetric(v *alertrule.Metric) *AlertRuleUpdate {
	if v != nil {
		_u.SetMetric(*v)
	}
	return _u
}

// SetThreshold sets the "threshold" field.
func (_u *AlertRuleUpdate) SetThreshold(v int64) *AlertRuleUpdate {
	_u.mutation.ResetThreshold()
	_u.mutation.SetThreshold(v)
	return _u
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (_u *AlertRuleUpdate) SetNillableThreshold(v *int64) *AlertRuleUpdate {
	if v != nil {
		_u.SetThreshold(*v)
	}
	return _u
}

// AddThreshold adds value to the "threshold" field.
func (_u *AlertRuleUpdate) AddThreshold(v int64) *AlertRuleUpdate {
	_u.mutation.AddThreshold(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AlertRuleUpdate) SetEnabled(v bool) *AlertRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AlertRuleUpdate) SetNillableEnabled(v *bool) *AlertRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AlertRuleUpdate) SetDescription(v string) *AlertRuleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AlertRuleUpdate) SetNillableDescription(v *string) *AlertRuleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AlertRuleUpdate) ClearDescription() *AlertRuleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the AlertRuleMutation object of the builder.
func (_u *AlertRuleUpdate) Mutation() *AlertRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlertRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlertRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlertRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := alertrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlertRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := alertrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AlertRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Metric(); ok {
		if err := alertrule.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "AlertRule.metric": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Threshold(); ok {
		if err := alertrule.ThresholdValidator(v); err != nil {
			return &ValidationError{Name: "threshold", err: fmt.Errorf(`ent: validator failed for field "AlertRule.threshold": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := alertrule.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AlertRule.description": %w`, err)}
		}
	}
	return nil
}

func (_u *AlertRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(alertrule.Table, alertrule.Columns, sqlgraph.NewFieldSpec(alertrule.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(alertrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(alertrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metric(); ok {
		_spec.SetField(alertrule.FieldMetric, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Threshold(); ok {
		_spec.SetField(alertrule.FieldThreshold, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedThreshold(); ok {
		_spec.AddField(alertrule.FieldThreshold, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(alertrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(alertrule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(alertrule.FieldDescription, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alertrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlertRuleUpdateOne is the builder for updating a single AlertRule entity.
type AlertRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlertRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlertRuleUpdateOne) SetUpdatedAt(v time.Time) *AlertRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AlertRuleUpdateOne) SetName(v string) *AlertRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AlertRuleUpdateOne) SetNillableName(v *string) *AlertRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMetric sets the "metric" field.
func (_u *AlertRuleUpdateOne) SetMetric(v alertrule.Metric) *AlertRuleUpdateOne {
	_u.mutation.SetMetric(v)
	return _u
}

// SetNillableMetric sets the "metric" field if the given value is not nil.
func (_u *AlertRuleUpdateOne) SetNillableMetric(v *alertrule.Metric) *AlertRuleUpdateOne {
	if v != nil {
		_u.SetMetric(*v)
	}
	return _u
}

// SetThreshold sets the "threshold" field.
func (_u *AlertRuleUpdateOne) SetThreshold(v int64) *AlertRuleUpdateOne {
	_u.mutation.ResetThreshold()
	_u.mutation.SetThreshold(v)
	return _u
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (_u *AlertRuleUpdateOne) SetNillableThreshold(v *int64) *AlertRuleUpdateOne {
	if v != nil {
		_u.SetThreshold(*v)
	}
	return _u
}

// AddThreshold adds value to the "threshold" field.
func (_u *AlertRuleUpdateOne) AddThreshold(v int64) *AlertRuleUpdateOne {
	_u.mutation.AddThreshold(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AlertRuleUpdateOne) SetEnabled(v bool) *AlertRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AlertRuleUpdateOne) SetNillableEnabled(v *bool) *AlertRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AlertRuleUpdateOne) SetDescription(v string) *AlertRuleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AlertRuleUpdateOne) SetNillableDescription(v *string) *AlertRuleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AlertRuleUpdateOne) ClearDescription() *AlertRuleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the AlertRuleMutation object of the builder.
func (_u *AlertRuleUpdateOne) Mutation() *AlertRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the AlertRuleUpdate builder.
func (_u *AlertRuleUpdateOne) Where(ps ...predicate.AlertRule) *AlertRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlertRuleUpdateOne) Select(field string, fields ...string) *AlertRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AlertRule entity.
func (_u *AlertRuleUpdateOne) Save(ctx context.Context) (*AlertRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertRuleUpdateOne) SaveX(ctx context.Context) *AlertRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlertRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlertRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := alertrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlertRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := alertrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AlertRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Metric(); ok {
		if err := alertrule.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "AlertRule.metric": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Threshold(); ok {
		if err := alertrule.ThresholdValidator(v); err != nil {
			return &ValidationError{Name: "threshold", err: fmt.Errorf(`ent: validator failed for field "AlertRule.threshold": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := alertrule.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AlertRule.description": %w`, err)}
		}
	}
	return nil
}

func (_u *AlertRuleUpdateOne) sqlSave(ctx context.Context) (_node *AlertRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(alertrule.Table, alertrule.Columns, sqlgraph.NewFieldSpec(alertrule.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AlertRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alertrule.FieldID)
		for _, f := range fields {
			if !alertrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alertrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(alertrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(alertrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metric(); ok {
		_spec.SetField(alertrule.FieldMetric, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Threshold(); ok {
		_spec.SetField(alertrule.FieldThreshold, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedThreshold(); ok {
		_spec.AddField(alertrule.FieldThreshold, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(alertrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(alertrule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(alertrule.FieldDescription, field.TypeString)
	}
	_node = &AlertRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alertrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
