// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/group"
	"github.com/school-api/school-api-v1/ent/groupplatform"
	"github.com/school-api/school-api-v1/ent/platform"
	"github.com/school-api/school-api-v1/ent/predicate"
)

// GroupPlatformUpdate is the builder for updating GroupPlatform entities.
type GroupPlatformUpdate struct {
	config
	hooks    []Hook
	mutation *GroupPlatformMutation
}

// Where appends a list predicates to the GroupPlatformUpdate builder.
func (_u *GroupPlatformUpdate) Where(ps ...predicate.GroupPlatform) *GroupPlatformUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupPlatformUpdate) SetUpdatedAt(v time.Time) *GroupPlatformUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupPlatformUpdate) SetGroupID(v uuid.UUID) *GroupPlatformUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupPlatformUpdate) SetNillableGroupID(v *uuid.UUID) *GroupPlatformUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *GroupPlatformUpdate) SetPlatformID(v uuid.UUID) *GroupPlatformUpdate {
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *GroupPlatformUpdate) SetNillablePlatformID(v *uuid.UUID) *GroupPlatformUpdate {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupPlatformUpdate) SetGroup(v *Group) *GroupPlatformUpdate {
	return _u.SetGroupID(v.ID)
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (_u *GroupPlatformUpdate) SetPlatform(v *Platform) *GroupPlatformUpdate {
	return _u.SetPlatformID(v.ID)
}

// Mutation returns the GroupPlatformMutation object of the builder.
func (_u *GroupPlatformUpdate) Mutation() *GroupPlatformMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupPlatformUpdate) ClearGroup() *GroupPlatformUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearPlatform clears the "platform" edge to the Platform entity.
func (_u *GroupPlatformUpdate) ClearPlatform() *GroupPlatformUpdate {
	_u.mutation.ClearPlatform()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupPlatformUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupPlatformUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupPlatformUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupPlatformUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupPlatformUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := groupplatform.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupPlatformUpdate) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupPlatform.group"`)
	}
	if _u.mutation.PlatformCleared() && len(_u.mutation.PlatformIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupPlatform.platform"`)
	}
	return nil
}

func (_u *GroupPlatformUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupplatform.Table, groupplatform.Columns, sqlgraph.NewFieldSpec(groupplatform.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupplatform.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupplatform.GroupTable,
			Columns: []string{groupplatform.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupplatform.GroupTable,
			Columns: []string{groupplatform.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlatformCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupplatform.PlatformTable,
			Columns: []string{groupplatform.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platform.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupplatform.PlatformTable,
			Columns: []string{groupplatform.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platform.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupplatform.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupPlatformUpdateOne is the builder for updating a single GroupPlatform entity.
type GroupPlatformUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupPlatformMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupPlatformUpdateOne) SetUpdatedAt(v time.Time) *GroupPlatformUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupPlatformUpdateOne) SetGroupID(v uuid.UUID) *GroupPlatformUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupPlatformUpdateOne) SetNillableGroupID(v *uuid.UUID) *GroupPlatformUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *GroupPlatformUpdateOne) SetPlatformID(v uuid.UUID) *GroupPlatformUpdateOne {
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *GroupPlatformUpdateOne) SetNillablePlatformID(v *uuid.UUID) *GroupPlatformUpdateOne {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupPlatformUpdateOne) SetGroup(v *Group) *GroupPlatformUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (_u *GroupPlatformUpdateOne) SetPlatform(v *Platform) *GroupPlatformUpdateOne {
	return _u.SetPlatformID(v.ID)
}

// Mutation returns the GroupPlatformMutation object of the builder.
func (_u *GroupPlatformUpdateOne) Mutation() *GroupPlatformMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupPlatformUpdateOne) ClearGroup() *GroupPlatformUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearPlatform clears the "platform" edge to the Platform entity.
func (_u *GroupPlatformUpdateOne) ClearPlatform() *GroupPlatformUpdateOne {
	_u.mutation.ClearPlatform()
	return _u
}

// Where appends a list predicates to the GroupPlatformUpdate builder.
func (_u *GroupPlatformUpdateOne) Where(ps ...predicate.GroupPlatform) *GroupPlatformUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupPlatformUpdateOne) Select(field string, fields ...string) *GroupPlatformUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupPlatform entity.
func (_u *GroupPlatformUpdateOne) Save(ctx context.Context) (*GroupPlatform, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupPlatformUpdateOne) SaveX(ctx context.Context) *GroupPlatform {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupPlatformUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupPlatformUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupPlatformUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := groupplatform.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupPlatformUpdateOne) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupPlatform.group"`)
	}
	if _u.mutation.PlatformCleared() && len(_u.mutation.PlatformIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupPlatform.platform"`)
	}
	return nil
}

func (_u *GroupPlatformUpdateOne) sqlSave(ctx context.Context) (_node *GroupPlatform, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupplatform.Table, groupplatform.Columns, sqlgraph.NewFieldSpec(groupplatform.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupPlatform.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupplatform.FieldID)
		for _, f := range fields {
			if !groupplatform.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupplatform.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupplatform.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupplatform.GroupTable,
			Columns: []string{groupplatform.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupplatform.GroupTable,
			Columns: []string{groupplatform.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlatformCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupplatform.PlatformTable,
			Columns: []string{groupplatform.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platform.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupplatform.PlatformTable,
			Columns: []string{groupplatform.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platform.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupPlatform{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupplatform.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
