// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/school-api/school-api-v1/ent/guidesection"
	"github.com/school-api/school-api-v1/ent/predicate"
)

// GuideSectionDelete is the builder for deleting a GuideSection entity.
type GuideSectionDelete struct {
	config
	hooks    []Hook
	mutation *GuideSectionMutation
}

// Where appends a list predicates to the GuideSectionDelete builder.
func (_d *GuideSectionDelete) Where(ps ...predicate.GuideSection) *GuideSectionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GuideSectionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GuideSectionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GuideSectionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(guidesection.Table, sqlgraph.NewFieldSpec(guidesection.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GuideSectionDeleteOne is the builder for deleting a single GuideSection entity.
type GuideSectionDeleteOne struct {
	_d *GuideSectionDelete
}

// Where appends a list predicates to the GuideSectionDelete builder.
func (_d *GuideSectionDeleteOne) Where(ps ...predicate.GuideSection) *GuideSectionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GuideSectionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{guidesection.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GuideSectionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
