// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/notification"
	"github.com/school-api/school-api-v1/ent/notificationread"
	"github.com/school-api/school-api-v1/ent/user"
)

// NotificationRead is the model entity for the NotificationRead schema.
type NotificationRead struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// NotificationID holds the value of the "notification_id" field.
	NotificationID uuid.UUID `json:"notification_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// ReadAt holds the value of the "read_at" field.
	ReadAt time.Time `json:"read_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationReadQuery when eager-loading is set.
	Edges        NotificationReadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NotificationReadEdges holds the relations/edges for other nodes in the graph.
type NotificationReadEdges struct {
	// Notification holds the value of the notification edge.
	Notification *Notification `json:"notification,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// NotificationOrErr returns the Notification value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationReadEdges) NotificationOrErr() (*Notification, error) {
	if e.Notification != nil {
		return e.Notification, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: notification.Label}
	}
	return nil, &NotLoadedError{edge: "notification"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationReadEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationRead) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationread.FieldReadAt:
			values[i] = new(sql.NullTime)
		case notificationread.FieldID, notificationread.FieldNotificationID, notificationread.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationRead fields.
func (_m *NotificationRead) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationread.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case notificationread.FieldNotificationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field notification_id", values[i])
			} else if value != nil {
				_m.NotificationID = *value
			}
		case notificationread.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case notificationread.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				_m.ReadAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationRead.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationRead) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNotification queries the "notification" edge of the NotificationRead entity.
func (_m *NotificationRead) QueryNotification() *NotificationQuery {
	return NewNotificationReadClient(_m.config).QueryNotification(_m)
}

// QueryUser queries the "user" edge of the NotificationRead entity.
func (_m *NotificationRead) QueryUser() *UserQuery {
	return NewNotificationReadClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this NotificationRead.
// Note that you need to call NotificationRead.Unwrap() before calling this method if this NotificationRead
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationRead) Update() *NotificationReadUpdateOne {
	return NewNotificationReadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationRead entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationRead) Unwrap() *NotificationRead {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationRead is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationRead) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationRead(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("notification_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotificationID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("read_at=")
	builder.WriteString(_m.ReadAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationReads is a parsable slice of NotificationRead.
type NotificationReads []*NotificationRead
