// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/notification"
	"github.com/school-api/school-api-v1/ent/notificationread"
	"github.com/school-api/school-api-v1/ent/user"
)

// NotificationReadCreate is the builder for creating a NotificationRead entity.
type NotificationReadCreate struct {
	config
	mutation *NotificationReadMutation
	hooks    []Hook
}

// SetNotificationID sets the "notification_id" field.
func (_c *NotificationReadCreate) SetNotificationID(v uuid.UUID) *NotificationReadCreate {
	_c.mutation.SetNotificationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *NotificationReadCreate) SetUserID(v uuid.UUID) *NotificationReadCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *NotificationReadCreate) SetReadAt(v time.Time) *NotificationReadCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_c *NotificationReadCreate) SetNillableReadAt(v *time.Time) *NotificationReadCreate {
	if v != nil {
		_c.SetReadAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationReadCreate) SetID(v uuid.UUID) *NotificationReadCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotificationReadCreate) SetNillableID(v *uuid.UUID) *NotificationReadCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetNotification sets the "notification" edge to the Notification entity.
func (_c *NotificationReadCreate) SetNotification(v *Notification) *NotificationReadCreate {
	return _c.SetNotificationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *NotificationReadCreate) SetUser(v *User) *NotificationReadCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the NotificationReadMutation object of the builder.
func (_c *NotificationReadCreate) Mutation() *NotificationReadMutation {
	return _c.mutation
}

// Save creates the NotificationRead in the database.
func (_c *NotificationReadCreate) Save(ctx context.Context) (*NotificationRead, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationReadCreate) SaveX(ctx context.Context) *NotificationRead {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationReadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationReadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationReadCreate) defaults() {
	if _, ok := _c.mutation.ReadAt(); !ok {
		v := notificationread.DefaultReadAt()
		_c.mutation.SetReadAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := notificationread.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationReadCreate) check() error {
	if _, ok := _c.mutation.NotificationID(); !ok {
		return &ValidationError{Name: "notification_id", err: errors.New(`ent: missing required field "NotificationRead.notification_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "NotificationRead.user_id"`)}
	}
	if _, ok := _c.mutation.ReadAt(); !ok {
		return &ValidationError{Name: "read_at", err: errors.New(`ent: missing required field "NotificationRead.read_at"`)}
	}
	if len(_c.mutation.NotificationIDs()) == 0 {
		return &ValidationError{Name: "notification", err: errors.New(`ent: missing required edge "NotificationRead.notification"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "NotificationRead.user"`)}
	}
	return nil
}

func (_c *NotificationReadCreate) sqlSave(ctx context.Context) (*NotificationRead, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationReadCreate) createSpec() (*NotificationRead, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationRead{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationread.Table, sqlgraph.NewFieldSpec(notificationread.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(notificationread.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = value
	}
	if nodes := _c.mutation.NotificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationread.NotificationTable,
			Columns: []string{notificationread.NotificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NotificationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationread.UserTable,
			Columns: []string{notificationread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationReadCreateBulk is the builder for creating many NotificationRead entities in bulk.
type NotificationReadCreateBulk struct {
	config
	err      error
	builders []*NotificationReadCreate
}

// Save creates the NotificationRead entities in the database.
func (_c *NotificationReadCreateBulk) Save(ctx context.Context) ([]*NotificationRead, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationRead, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationReadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationReadCreateBulk) SaveX(ctx context.Context) []*NotificationRead {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationReadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationReadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
