// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/calllog"
	"github.com/school-api/school-api-v1/ent/quotarecord"
	"github.com/school-api/school-api-v1/ent/user"
	"github.com/school-api/school-api-v1/ent/usertoken"
)

// QuotaRecordCreate is the builder for creating a QuotaRecord entity.
type QuotaRecordCreate struct {
	config
	mutation *QuotaRecordMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuotaRecordCreate) SetCreatedAt(v time.Time) *QuotaRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuotaRecordCreate) SetNillableCreatedAt(v *time.Time) *QuotaRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuotaRecordCreate) SetUpdatedAt(v time.Time) *QuotaRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuotaRecordCreate) SetNillableUpdatedAt(v *time.Time) *QuotaRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *QuotaRecordCreate) SetUserID(v uuid.UUID) *QuotaRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTokenID sets the "token_id" field.
func (_c *QuotaRecordCreate) SetTokenID(v uuid.UUID) *QuotaRecordCreate {
	_c.mutation.SetTokenID(v)
	return _c
}

// SetCallLogID sets the "call_log_id" field.
func (_c *QuotaRecordCreate) SetCallLogID(v uuid.UUID) *QuotaRecordCreate {
	_c.mutation.SetCallLogID(v)
	return _c
}

// SetNillableCallLogID sets the "call_log_id" field if the given value is not nil.
func (_c *QuotaRecordCreate) SetNillableCallLogID(v *uuid.UUID) *QuotaRecordCreate {
	if v != nil {
		_c.SetCallLogID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *QuotaRecordCreate) SetType(v quotarecord.Type) *QuotaRecordCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *QuotaRecordCreate) SetAmount(v int64) *QuotaRecordCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetQuotaAfter sets the "quota_after" field.
func (_c *QuotaRecordCreate) SetQuotaAfter(v int64) *QuotaRecordCreate {
	_c.mutation.SetQuotaAfter(v)
	return _c
}

// SetNillableQuotaAfter sets the "quota_after" field if the given value is not nil.
func (_c *QuotaRecordCreate) SetNillableQuotaAfter(v *int64) *QuotaRecordCreate {
	if v != nil {
		_c.SetQuotaAfter(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuotaRecordCreate) SetID(v uuid.UUID) *QuotaRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *QuotaRecordCreate) SetNillableID(v *uuid.UUID) *QuotaRecordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *QuotaRecordCreate) SetUser(v *User) *QuotaRecordCreate {
	return _c.SetUserID(v.ID)
}

// SetToken sets the "token" edge to the UserToken entity.
func (_c *QuotaRecordCreate) SetToken(v *UserToken) *QuotaRecordCreate {
	return _c.SetTokenID(v.ID)
}

// SetCallLog sets the "call_log" edge to the CallLog entity.
func (_c *QuotaRecordCreate) SetCallLog(v *CallLog) *QuotaRecordCreate {
	return _c.SetCallLogID(v.ID)
}

// Mutation returns the QuotaRecordMutation object of the builder.
func (_c *QuotaRecordCreate) Mutation() *QuotaRecordMutation {
	return _c.mutation
}

// Save creates the QuotaRecord in the database.
func (_c *QuotaRecordCreate) Save(ctx context.Context) (*QuotaRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuotaRecordCreate) SaveX(ctx context.Context) *QuotaRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuotaRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quotarecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := quotarecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.QuotaAfter(); !ok {
		v := quotarecord.DefaultQuotaAfter
		_c.mutation.SetQuotaAfter(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := quotarecord.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuotaRecordCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuotaRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QuotaRecord.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "QuotaRecord.user_id"`)}
	}
	if _, ok := _c.mutation.TokenID(); !ok {
		return &ValidationError{Name: "token_id", err: errors.New(`ent: missing required field "QuotaRecord.token_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "QuotaRecord.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := quotarecord.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "QuotaRecord.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "QuotaRecord.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := quotarecord.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "QuotaRecord.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuotaAfter(); !ok {
		return &ValidationError{Name: "quota_after", err: errors.New(`ent: missing required field "QuotaRecord.quota_after"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "QuotaRecord.user"`)}
	}
	if len(_c.mutation.TokenIDs()) == 0 {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required edge "QuotaRecord.token"`)}
	}
	return nil
}

func (_c *QuotaRecordCreate) sqlSave(ctx context.Context) (*QuotaRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuotaRecordCreate) createSpec() (*QuotaRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &QuotaRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quotarecord.Table, sqlgraph.NewFieldSpec(quotarecord.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quotarecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(quotarecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(quotarecord.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(quotarecord.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.QuotaAfter(); ok {
		_spec.SetField(quotarecord.FieldQuotaAfter, field.TypeInt64, value)
		_node.QuotaAfter = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarecord.UserTable,
			Columns: []string{quotarecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarecord.TokenTable,
			Columns: []string{quotarecord.TokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TokenID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CallLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarecord.CallLogTable,
			Columns: []string{quotarecord.CallLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calllog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CallLogID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuotaRecordCreateBulk is the builder for creating many QuotaRecord entities in bulk.
type QuotaRecordCreateBulk struct {
	config
	err      error
	builders []*QuotaRecordCreate
}

// Save creates the QuotaRecord entities in the database.
func (_c *QuotaRecordCreateBulk) Save(ctx context.Context) ([]*QuotaRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QuotaRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuotaRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuotaRecordCreateBulk) SaveX(ctx context.Context) []*QuotaRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
