// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/adminuser"
	"github.com/school-api/school-api-v1/ent/predicate"
	"github.com/school-api/school-api-v1/ent/quotarequest"
	"github.com/school-api/school-api-v1/ent/user"
	"github.com/school-api/school-api-v1/ent/usertoken"
)

// QuotaRequestUpdate is the builder for updating QuotaRequest entities.
type QuotaRequestUpdate struct {
	config
	hooks    []Hook
	mutation *QuotaRequestMutation
}

// Where appends a list predicates to the QuotaRequestUpdate builder.
func (_u *QuotaRequestUpdate) Where(ps ...predicate.QuotaRequest) *QuotaRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaRequestUpdate) SetUpdatedAt(v time.Time) *QuotaRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *QuotaRequestUpdate) SetUserID(v uuid.UUID) *QuotaRequestUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *QuotaRequestUpdate) SetNillableUserID(v *uuid.UUID) *QuotaRequestUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTokenID sets the "token_id" field.
func (_u *QuotaRequestUpdate) SetTokenID(v uuid.UUID) *QuotaRequestUpdate {
	_u.mutation.SetTokenID(v)
	return _u
}

// SetNillableTokenID sets the "token_id" field if the given value is not nil.
func (_u *QuotaRequestUpdate) SetNillableTokenID(v *uuid.UUID) *QuotaRequestUpdate {
	if v != nil {
		_u.SetTokenID(*v)
	}
	return _u
}

// SetRequestedAmount sets the "requested_amount" field.
func (_u *QuotaRequestUpdate) SetRequestedAmount(v int64) *QuotaRequestUpdate {
	_u.mutation.ResetRequestedAmount()
	_u.mutation.SetRequestedAmount(v)
	return _u
}

// SetNillableRequestedAmount sets the "requested_amount" field if the given value is not nil.
func (_u *QuotaRequestUpdate) SetNillableRequestedAmount(v *int64) *QuotaRequestUpdate {
	if v != nil {
		_u.SetRequestedAmount(*v)
	}
	return _u
}

// AddRequestedAmount adds value to the "requested_amount" field.
func (_u *QuotaRequestUpdate) AddRequestedAmount(v int64) *QuotaRequestUpdate {
	_u.mutation.AddRequestedAmount(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *QuotaRequestUpdate) SetReason(v string) *QuotaRequestUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *QuotaRequestUpdate) SetNillableReason(v *string) *QuotaRequestUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *QuotaRequestUpdate) ClearReason() *QuotaRequestUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaRequestUpdate) SetStatus(v quotarequest.Status) *QuotaRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaRequestUpdate) SetNillableStatus(v *quotarequest.Status) *QuotaRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *QuotaRequestUpdate) SetReviewedBy(v uuid.UUID) *QuotaRequestUpdate {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *QuotaRequestUpdate) SetNillableReviewedBy(v *uuid.UUID) *QuotaRequestUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *QuotaRequestUpdate) ClearReviewedBy() *QuotaRequestUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *QuotaRequestUpdate) SetReviewedAt(v time.Time) *QuotaRequestUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *QuotaRequestUpdate) SetNillableReviewedAt(v *time.Time) *QuotaRequestUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *QuotaRequestUpdate) ClearReviewedAt() *QuotaRequestUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *QuotaRequestUpdate) SetUser(v *User) *QuotaRequestUpdate {
	return _u.SetUserID(v.ID)
}

// SetToken sets the "token" edge to the UserToken entity.
func (_u *QuotaRequestUpdate) SetToken(v *UserToken) *QuotaRequestUpdate {
	return _u.SetTokenID(v.ID)
}

// SetReviewerID sets the "reviewer" edge to the AdminUser entity by ID.
func (_u *QuotaRequestUpdate) SetReviewerID(id uuid.UUID) *QuotaRequestUpdate {
	_u.mutation.SetReviewerID(id)
	return _u
}

// SetNillableReviewerID sets the "reviewer" edge to the AdminUser entity by ID if the given value is not nil.
func (_u *QuotaRequestUpdate) SetNillableReviewerID(id *uuid.UUID) *QuotaRequestUpdate {
	if id != nil {
		_u = _u.SetReviewerID(*id)
	}
	return _u
}

// SetReviewer sets the "reviewer" edge to the AdminUser entity.
func (_u *QuotaRequestUpdate) SetReviewer(v *AdminUser) *QuotaRequestUpdate {
	return _u.SetReviewerID(v.ID)
}

// Mutation returns the QuotaRequestMutation object of the builder.
func (_u *QuotaRequestUpdate) Mutation() *QuotaRequestMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *QuotaRequestUpdate) ClearUser() *QuotaRequestUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearToken clears the "token" edge to the UserToken entity.
func (_u *QuotaRequestUpdate) ClearToken() *QuotaRequestUpdate {
	_u.mutation.ClearToken()
	return _u
}

// ClearReviewer clears the "reviewer" edge to the AdminUser entity.
func (_u *QuotaRequestUpdate) ClearReviewer() *QuotaRequestUpdate {
	_u.mutation.ClearReviewer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuotaRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuotaRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotarequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaRequestUpdate) check() error {
	if v, ok := _u.mutation.RequestedAmount(); ok {
		if err := quotarequest.RequestedAmountValidator(v); err != nil {
			return &ValidationError{Name: "requested_amount", err: fmt.Errorf(`ent: validator failed for field "QuotaRequest.requested_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := quotarequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "QuotaRequest.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotarequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaRequest.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuotaRequest.user"`)
	}
	if _u.mutation.TokenCleared() && len(_u.mutation.TokenIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuotaRequest.token"`)
	}
	return nil
}

func (_u *QuotaRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotarequest.Table, quotarequest.Columns, sqlgraph.NewFieldSpec(quotarequest.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotarequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestedAmount(); ok {
		_spec.SetField(quotarequest.FieldRequestedAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestedAmount(); ok {
		_spec.AddField(quotarequest.FieldRequestedAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(quotarequest.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(quotarequest.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotarequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(quotarequest.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(quotarequest.FieldReviewedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.UserTable,
			Columns: []string{quotarequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.UserTable,
			Columns: []string{quotarequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.TokenTable,
			Columns: []string{quotarequest.TokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.TokenTable,
			Columns: []string{quotarequest.TokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.ReviewerTable,
			Columns: []string{quotarequest.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.ReviewerTable,
			Columns: []string{quotarequest.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotarequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuotaRequestUpdateOne is the builder for updating a single QuotaRequest entity.
type QuotaRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuotaRequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaRequestUpdateOne) SetUpdatedAt(v time.Time) *QuotaRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *QuotaRequestUpdateOne) SetUserID(v uuid.UUID) *QuotaRequestUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *QuotaRequestUpdateOne) SetNillableUserID(v *uuid.UUID) *QuotaRequestUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTokenID sets the "token_id" field.
func (_u *QuotaRequestUpdateOne) SetTokenID(v uuid.UUID) *QuotaRequestUpdateOne {
	_u.mutation.SetTokenID(v)
	return _u
}

// SetNillableTokenID sets the "token_id" field if the given value is not nil.
func (_u *QuotaRequestUpdateOne) SetNillableTokenID(v *uuid.UUID) *QuotaRequestUpdateOne {
	if v != nil {
		_u.SetTokenID(*v)
	}
	return _u
}

// SetRequestedAmount sets the "requested_amount" field.
func (_u *QuotaRequestUpdateOne) SetRequestedAmount(v int64) *QuotaRequestUpdateOne {
	_u.mutation.ResetRequestedAmount()
	_u.mutation.SetRequestedAmount(v)
	return _u
}

// SetNillableRequestedAmount sets the "requested_amount" field if the given value is not nil.
func (_u *QuotaRequestUpdateOne) SetNillableRequestedAmount(v *int64) *QuotaRequestUpdateOne {
	if v != nil {
		_u.SetRequestedAmount(*v)
	}
	return _u
}

// AddRequestedAmount adds value to the "requested_amount" field.
func (_u *QuotaRequestUpdateOne) AddRequestedAmount(v int64) *QuotaRequestUpdateOne {
	_u.mutation.AddRequestedAmount(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *QuotaRequestUpdateOne) SetReason(v string) *QuotaRequestUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *QuotaRequestUpdateOne) SetNillableReason(v *string) *QuotaRequestUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *QuotaRequestUpdateOne) ClearReason() *QuotaRequestUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaRequestUpdateOne) SetStatus(v quotarequest.Status) *QuotaRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaRequestUpdateOne) SetNillableStatus(v *quotarequest.Status) *QuotaRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *QuotaRequestUpdateOne) SetReviewedBy(v uuid.UUID) *QuotaRequestUpdateOne {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *QuotaRequestUpdateOne) SetNillableReviewedBy(v *uuid.UUID) *QuotaRequestUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *QuotaRequestUpdateOne) ClearReviewedBy() *QuotaRequestUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *QuotaRequestUpdateOne) SetReviewedAt(v time.Time) *QuotaRequestUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *QuotaRequestUpdateOne) SetNillableReviewedAt(v *time.Time) *QuotaRequestUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *QuotaRequestUpdateOne) ClearReviewedAt() *QuotaRequestUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *QuotaRequestUpdateOne) SetUser(v *User) *QuotaRequestUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetToken sets the "token" edge to the UserToken entity.
func (_u *QuotaRequestUpdateOne) SetToken(v *UserToken) *QuotaRequestUpdateOne {
	return _u.SetTokenID(v.ID)
}

// SetReviewerID sets the "reviewer" edge to the AdminUser entity by ID.
func (_u *QuotaRequestUpdateOne) SetReviewerID(id uuid.UUID) *QuotaRequestUpdateOne {
	_u.mutation.SetReviewerID(id)
	return _u
}

// SetNillableReviewerID sets the "reviewer" edge to the AdminUser entity by ID if the given value is not nil.
func (_u *QuotaRequestUpdateOne) SetNillableReviewerID(id *uuid.UUID) *QuotaRequestUpdateOne {
	if id != nil {
		_u = _u.SetReviewerID(*id)
	}
	return _u
}

// SetReviewer sets the "reviewer" edge to the AdminUser entity.
func (_u *QuotaRequestUpdateOne) SetReviewer(v *AdminUser) *QuotaRequestUpdateOne {
	return _u.SetReviewerID(v.ID)
}

// Mutation returns the QuotaRequestMutation object of the builder.
func (_u *QuotaRequestUpdateOne) Mutation() *QuotaRequestMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *QuotaRequestUpdateOne) ClearUser() *QuotaRequestUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearToken clears the "token" edge to the UserToken entity.
func (_u *QuotaRequestUpdateOne) ClearToken() *QuotaRequestUpdateOne {
	_u.mutation.ClearToken()
	return _u
}

// ClearReviewer clears the "reviewer" edge to the AdminUser entity.
func (_u *QuotaRequestUpdateOne) ClearReviewer() *QuotaRequestUpdateOne {
	_u.mutation.ClearReviewer()
	return _u
}

// Where appends a list predicates to the QuotaRequestUpdate builder.
func (_u *QuotaRequestUpdateOne) Where(ps ...predicate.QuotaRequest) *QuotaRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuotaRequestUpdateOne) Select(field string, fields ...string) *QuotaRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuotaRequest entity.
func (_u *QuotaRequestUpdateOne) Save(ctx context.Context) (*QuotaRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaRequestUpdateOne) SaveX(ctx context.Context) *QuotaRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuotaRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotarequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaRequestUpdateOne) check() error {
	if v, ok := _u.mutation.RequestedAmount(); ok {
		if err := quotarequest.RequestedAmountValidator(v); err != nil {
			return &ValidationError{Name: "requested_amount", err: fmt.Errorf(`ent: validator failed for field "QuotaRequest.requested_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := quotarequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "QuotaRequest.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotarequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaRequest.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuotaRequest.user"`)
	}
	if _u.mutation.TokenCleared() && len(_u.mutation.TokenIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuotaRequest.token"`)
	}
	return nil
}

func (_u *QuotaRequestUpdateOne) sqlSave(ctx context.Context) (_node *QuotaRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotarequest.Table, quotarequest.Columns, sqlgraph.NewFieldSpec(quotarequest.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuotaRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotarequest.FieldID)
		for _, f := range fields {
			if !quotarequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quotarequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotarequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestedAmount(); ok {
		_spec.SetField(quotarequest.FieldRequestedAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestedAmount(); ok {
		_spec.AddField(quotarequest.FieldRequestedAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(quotarequest.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(quotarequest.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotarequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(quotarequest.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(quotarequest.FieldReviewedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.UserTable,
			Columns: []string{quotarequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.UserTable,
			Columns: []string{quotarequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.TokenTable,
			Columns: []string{quotarequest.TokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.TokenTable,
			Columns: []string{quotarequest.TokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.ReviewerTable,
			Columns: []string{quotarequest.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotarequest.ReviewerTable,
			Columns: []string{quotarequest.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &QuotaRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotarequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
