// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/calllog"
	"github.com/school-api/school-api-v1/ent/predicate"
	"github.com/school-api/school-api-v1/ent/quotarecord"
	"github.com/school-api/school-api-v1/ent/user"
	"github.com/school-api/school-api-v1/ent/usertoken"
)

// QuotaRecordQuery is the builder for querying QuotaRecord entities.
type QuotaRecordQuery struct {
	config
	ctx         *QueryContext
	order       []quotarecord.OrderOption
	inters      []Interceptor
	predicates  []predicate.QuotaRecord
	withUser    *UserQuery
	withToken   *UserTokenQuery
	withCallLog *CallLogQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuotaRecordQuery builder.
func (_q *QuotaRecordQuery) Where(ps ...predicate.QuotaRecord) *QuotaRecordQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *QuotaRecordQuery) Limit(limit int) *QuotaRecordQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *QuotaRecordQuery) Offset(offset int) *QuotaRecordQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *QuotaRecordQuery) Unique(unique bool) *QuotaRecordQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *QuotaRecordQuery) Order(o ...quotarecord.OrderOption) *QuotaRecordQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *QuotaRecordQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quotarecord.Table, quotarecord.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, quotarecord.UserTable, quotarecord.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryToken chains the current query on the "token" edge.
func (_q *QuotaRecordQuery) QueryToken() *UserTokenQuery {
	query := (&UserTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quotarecord.Table, quotarecord.FieldID, selector),
			sqlgraph.To(usertoken.Table, usertoken.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, quotarecord.TokenTable, quotarecord.TokenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCallLog chains the current query on the "call_log" edge.
func (_q *QuotaRecordQuery) QueryCallLog() *CallLogQuery {
	query := (&CallLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quotarecord.Table, quotarecord.FieldID, selector),
			sqlgraph.To(calllog.Table, calllog.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, quotarecord.CallLogTable, quotarecord.CallLogColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QuotaRecord entity from the query.
// Returns a *NotFoundError when no QuotaRecord was found.
func (_q *QuotaRecordQuery) First(ctx context.Context) (*QuotaRecord, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{quotarecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *QuotaRecordQuery) FirstX(ctx context.Context) *QuotaRecord {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuotaRecord ID from the query.
// Returns a *NotFoundError when no QuotaRecord ID was found.
func (_q *QuotaRecordQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{quotarecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *QuotaRecordQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuotaRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuotaRecord entity is found.
// Returns a *NotFoundError when no QuotaRecord entities are found.
func (_q *QuotaRecordQuery) Only(ctx context.Context) (*QuotaRecord, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{quotarecord.Label}
	default:
		return nil, &NotSingularError{quotarecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *QuotaRecordQuery) OnlyX(ctx context.Context) *QuotaRecord {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuotaRecord ID in the query.
// Returns a *NotSingularError when more than one QuotaRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *QuotaRecordQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{quotarecord.Label}
	default:
		err = &NotSingularError{quotarecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *QuotaRecordQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuotaRecords.
func (_q *QuotaRecordQuery) All(ctx context.Context) ([]*QuotaRecord, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QuotaRecord, *QuotaRecordQuery]()
	return withInterceptors[[]*QuotaRecord](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *QuotaRecordQuery) AllX(ctx context.Context) []*QuotaRecord {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuotaRecord IDs.
func (_q *QuotaRecordQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(quotarecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *QuotaRecordQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *QuotaRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*QuotaRecordQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *QuotaRecordQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *QuotaRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *QuotaRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuotaRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *QuotaRecordQuery) Clone() *QuotaRecordQuery {
	if _q == nil {
		return nil
	}
	return &QuotaRecordQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]quotarecord.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.QuotaRecord{}, _q.predicates...),
		withUser:    _q.withUser.Clone(),
		withToken:   _q.withToken.Clone(),
		withCallLog: _q.withCallLog.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuotaRecordQuery) WithUser(opts ...func(*UserQuery)) *QuotaRecordQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithToken tells the query-builder to eager-load the nodes that are connected to
// the "token" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuotaRecordQuery) WithToken(opts ...func(*UserTokenQuery)) *QuotaRecordQuery {
	query := (&UserTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withToken = query
	return _q
}

// WithCallLog tells the query-builder to eager-load the nodes that are connected to
// the "call_log" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuotaRecordQuery) WithCallLog(opts ...func(*CallLogQuery)) *QuotaRecordQuery {
	query := (&CallLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCallLog = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuotaRecord.Query().
//		GroupBy(quotarecord.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *QuotaRecordQuery) GroupBy(field string, fields ...string) *QuotaRecordGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuotaRecordGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = quotarecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.QuotaRecord.Query().
//		Select(quotarecord.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *QuotaRecordQuery) Select(fields ...string) *QuotaRecordSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &QuotaRecordSelect{QuotaRecordQuery: _q}
	sbuild.label = quotarecord.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuotaRecordSelect configured with the given aggregations.
func (_q *QuotaRecordQuery) Aggregate(fns ...AggregateFunc) *QuotaRecordSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *QuotaRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !quotarecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *QuotaRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuotaRecord, error) {
	var (
		nodes       = []*QuotaRecord{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUser != nil,
			_q.withToken != nil,
			_q.withCallLog != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuotaRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuotaRecord{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *QuotaRecord, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withToken; query != nil {
		if err := _q.loadToken(ctx, query, nodes, nil,
			func(n *QuotaRecord, e *UserToken) { n.Edges.Token = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCallLog; query != nil {
		if err := _q.loadCallLog(ctx, query, nodes, nil,
			func(n *QuotaRecord, e *CallLog) { n.Edges.CallLog = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *QuotaRecordQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*QuotaRecord, init func(*QuotaRecord), assign func(*QuotaRecord, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*QuotaRecord)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *QuotaRecordQuery) loadToken(ctx context.Context, query *UserTokenQuery, nodes []*QuotaRecord, init func(*QuotaRecord), assign func(*QuotaRecord, *UserToken)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*QuotaRecord)
	for i := range nodes {
		fk := nodes[i].TokenID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usertoken.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "token_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *QuotaRecordQuery) loadCallLog(ctx context.Context, query *CallLogQuery, nodes []*QuotaRecord, init func(*QuotaRecord), assign func(*QuotaRecord, *CallLog)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*QuotaRecord)
	for i := range nodes {
		if nodes[i].CallLogID == nil {
			continue
		}
		fk := *nodes[i].CallLogID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(calllog.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "call_log_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *QuotaRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *QuotaRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(quotarecord.Table, quotarecord.Columns, sqlgraph.NewFieldSpec(quotarecord.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotarecord.FieldID)
		for i := range fields {
			if fields[i] != quotarecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(quotarecord.FieldUserID)
		}
		if _q.withToken != nil {
			_spec.Node.AddColumnOnce(quotarecord.FieldTokenID)
		}
		if _q.withCallLog != nil {
			_spec.Node.AddColumnOnce(quotarecord.FieldCallLogID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *QuotaRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(quotarecord.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = quotarecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QuotaRecordGroupBy is the group-by builder for QuotaRecord entities.
type QuotaRecordGroupBy struct {
	selector
	build *QuotaRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *QuotaRecordGroupBy) Aggregate(fns ...AggregateFunc) *QuotaRecordGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *QuotaRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuotaRecordQuery, *QuotaRecordGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *QuotaRecordGroupBy) sqlScan(ctx context.Context, root *QuotaRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuotaRecordSelect is the builder for selecting fields of QuotaRecord entities.
type QuotaRecordSelect struct {
	*QuotaRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *QuotaRecordSelect) Aggregate(fns ...AggregateFunc) *QuotaRecordSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *QuotaRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuotaRecordQuery, *QuotaRecordSelect](ctx, _s.QuotaRecordQuery, _s, _s.inters, v)
}

func (_s *QuotaRecordSelect) sqlScan(ctx context.Context, root *QuotaRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
