// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/account"
	"github.com/school-api/school-api-v1/ent/adminuser"
	"github.com/school-api/school-api-v1/ent/aimodel"
	"github.com/school-api/school-api-v1/ent/alertrecord"
	"github.com/school-api/school-api-v1/ent/alertrule"
	"github.com/school-api/school-api-v1/ent/auditlog"
	"github.com/school-api/school-api-v1/ent/balancerecord"
	"github.com/school-api/school-api-v1/ent/calllog"
	"github.com/school-api/school-api-v1/ent/department"
	"github.com/school-api/school-api-v1/ent/group"
	"github.com/school-api/school-api-v1/ent/groupplatform"
	"github.com/school-api/school-api-v1/ent/guidesection"
	"github.com/school-api/school-api-v1/ent/notification"
	"github.com/school-api/school-api-v1/ent/notificationread"
	"github.com/school-api/school-api-v1/ent/platform"
	"github.com/school-api/school-api-v1/ent/quotarecord"
	"github.com/school-api/school-api-v1/ent/quotarequest"
	"github.com/school-api/school-api-v1/ent/rechargeorder"
	"github.com/school-api/school-api-v1/ent/refundrequest"
	"github.com/school-api/school-api-v1/ent/schema"
	"github.com/school-api/school-api-v1/ent/setting"
	"github.com/school-api/school-api-v1/ent/user"
	"github.com/school-api/school-api-v1/ent/usertoken"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	aimodelMixin := schema.AIModel{}.Mixin()
	aimodelMixinFields0 := aimodelMixin[0].Fields()
	_ = aimodelMixinFields0
	aimodelFields := schema.AIModel{}.Fields()
	_ = aimodelFields
	// aimodelDescCreatedAt is the schema descriptor for created_at field.
	aimodelDescCreatedAt := aimodelMixinFields0[0].Descriptor()
	// aimodel.DefaultCreatedAt holds the default value on creation for the created_at field.
	aimodel.DefaultCreatedAt = aimodelDescCreatedAt.Default.(func() time.Time)
	// aimodelDescUpdatedAt is the schema descriptor for updated_at field.
	aimodelDescUpdatedAt := aimodelMixinFields0[1].Descriptor()
	// aimodel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	aimodel.DefaultUpdatedAt = aimodelDescUpdatedAt.Default.(func() time.Time)
	// aimodel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	aimodel.UpdateDefaultUpdatedAt = aimodelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// aimodelDescName is the schema descriptor for name field.
	aimodelDescName := aimodelFields[1].Descriptor()
	// aimodel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	aimodel.NameValidator = func() func(string) error {
		validators := aimodelDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// aimodelDescUpstreamName is the schema descriptor for upstream_name field.
	aimodelDescUpstreamName := aimodelFields[2].Descriptor()
	// aimodel.UpstreamNameValidator is a validator for the "upstream_name" field. It is called by the builders before save.
	aimodel.UpstreamNameValidator = func() func(string) error {
		validators := aimodelDescUpstreamName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(upstream_name string) error {
			for _, fn := range fns {
				if err := fn(upstream_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// aimodelDescInputPrice is the schema descriptor for input_price field.
	aimodelDescInputPrice := aimodelFields[4].Descriptor()
	// aimodel.DefaultInputPrice holds the default value on creation for the input_price field.
	aimodel.DefaultInputPrice = aimodelDescInputPrice.Default.(int64)
	// aimodelDescOutputPrice is the schema descriptor for output_price field.
	aimodelDescOutputPrice := aimodelFields[5].Descriptor()
	// aimodel.DefaultOutputPrice holds the default value on creation for the output_price field.
	aimodel.DefaultOutputPrice = aimodelDescOutputPrice.Default.(int64)
	// aimodelDescIsEnabled is the schema descriptor for is_enabled field.
	aimodelDescIsEnabled := aimodelFields[6].Descriptor()
	// aimodel.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	aimodel.DefaultIsEnabled = aimodelDescIsEnabled.Default.(bool)
	// aimodelDescID is the schema descriptor for id field.
	aimodelDescID := aimodelFields[0].Descriptor()
	// aimodel.DefaultID holds the default value on creation for the id field.
	aimodel.DefaultID = aimodelDescID.Default.(func() uuid.UUID)
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountMixinFields0[0].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountMixinFields0[1].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[2].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = func() func(string) error {
		validators := accountDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescAPIKeyEncrypted is the schema descriptor for api_key_encrypted field.
	accountDescAPIKeyEncrypted := accountFields[3].Descriptor()
	// account.APIKeyEncryptedValidator is a validator for the "api_key_encrypted" field. It is called by the builders before save.
	account.APIKeyEncryptedValidator = func() func(string) error {
		validators := accountDescAPIKeyEncrypted.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(api_key_encrypted string) error {
			for _, fn := range fns {
				if err := fn(api_key_encrypted); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescWeight is the schema descriptor for weight field.
	accountDescWeight := accountFields[4].Descriptor()
	// account.DefaultWeight holds the default value on creation for the weight field.
	account.DefaultWeight = accountDescWeight.Default.(int)
	// accountDescMaxRpm is the schema descriptor for max_rpm field.
	accountDescMaxRpm := accountFields[5].Descriptor()
	// account.DefaultMaxRpm holds the default value on creation for the max_rpm field.
	account.DefaultMaxRpm = accountDescMaxRpm.Default.(int)
	// accountDescErrorCount is the schema descriptor for error_count field.
	accountDescErrorCount := accountFields[7].Descriptor()
	// account.DefaultErrorCount holds the default value on creation for the error_count field.
	account.DefaultErrorCount = accountDescErrorCount.Default.(int)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	adminuserMixin := schema.AdminUser{}.Mixin()
	adminuserMixinFields0 := adminuserMixin[0].Fields()
	_ = adminuserMixinFields0
	adminuserFields := schema.AdminUser{}.Fields()
	_ = adminuserFields
	// adminuserDescCreatedAt is the schema descriptor for created_at field.
	adminuserDescCreatedAt := adminuserMixinFields0[0].Descriptor()
	// adminuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminuser.DefaultCreatedAt = adminuserDescCreatedAt.Default.(func() time.Time)
	// adminuserDescUpdatedAt is the schema descriptor for updated_at field.
	adminuserDescUpdatedAt := adminuserMixinFields0[1].Descriptor()
	// adminuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminuser.DefaultUpdatedAt = adminuserDescUpdatedAt.Default.(func() time.Time)
	// adminuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminuser.UpdateDefaultUpdatedAt = adminuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminuserDescUsername is the schema descriptor for username field.
	adminuserDescUsername := adminuserFields[1].Descriptor()
	// adminuser.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	adminuser.UsernameValidator = func() func(string) error {
		validators := adminuserDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminuserDescPasswordHash is the schema descriptor for password_hash field.
	adminuserDescPasswordHash := adminuserFields[2].Descriptor()
	// adminuser.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	adminuser.PasswordHashValidator = func() func(string) error {
		validators := adminuserDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminuserDescID is the schema descriptor for id field.
	adminuserDescID := adminuserFields[0].Descriptor()
	// adminuser.DefaultID holds the default value on creation for the id field.
	adminuser.DefaultID = adminuserDescID.Default.(func() uuid.UUID)
	alertrecordMixin := schema.AlertRecord{}.Mixin()
	alertrecordMixinFields0 := alertrecordMixin[0].Fields()
	_ = alertrecordMixinFields0
	alertrecordFields := schema.AlertRecord{}.Fields()
	_ = alertrecordFields
	// alertrecordDescCreatedAt is the schema descriptor for created_at field.
	alertrecordDescCreatedAt := alertrecordMixinFields0[0].Descriptor()
	// alertrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	alertrecord.DefaultCreatedAt = alertrecordDescCreatedAt.Default.(func() time.Time)
	// alertrecordDescUpdatedAt is the schema descriptor for updated_at field.
	alertrecordDescUpdatedAt := alertrecordMixinFields0[1].Descriptor()
	// alertrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	alertrecord.DefaultUpdatedAt = alertrecordDescUpdatedAt.Default.(func() time.Time)
	// alertrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	alertrecord.UpdateDefaultUpdatedAt = alertrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// alertrecordDescMetric is the schema descriptor for metric field.
	alertrecordDescMetric := alertrecordFields[2].Descriptor()
	// alertrecord.MetricValidator is a validator for the "metric" field. It is called by the builders before save.
	alertrecord.MetricValidator = alertrecordDescMetric.Validators[0].(func(string) error)
	// alertrecordDescTriggeredValue is the schema descriptor for triggered_value field.
	alertrecordDescTriggeredValue := alertrecordFields[6].Descriptor()
	// alertrecord.DefaultTriggeredValue holds the default value on creation for the triggered_value field.
	alertrecord.DefaultTriggeredValue = alertrecordDescTriggeredValue.Default.(int64)
	// alertrecordDescMessage is the schema descriptor for message field.
	alertrecordDescMessage := alertrecordFields[7].Descriptor()
	// alertrecord.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	alertrecord.MessageValidator = alertrecordDescMessage.Validators[0].(func(string) error)
	// alertrecordDescIsResolved is the schema descriptor for is_resolved field.
	alertrecordDescIsResolved := alertrecordFields[8].Descriptor()
	// alertrecord.DefaultIsResolved holds the default value on creation for the is_resolved field.
	alertrecord.DefaultIsResolved = alertrecordDescIsResolved.Default.(bool)
	// alertrecordDescID is the schema descriptor for id field.
	alertrecordDescID := alertrecordFields[0].Descriptor()
	// alertrecord.DefaultID holds the default value on creation for the id field.
	alertrecord.DefaultID = alertrecordDescID.Default.(func() uuid.UUID)
	alertruleMixin := schema.AlertRule{}.Mixin()
	alertruleMixinFields0 := alertruleMixin[0].Fields()
	_ = alertruleMixinFields0
	alertruleFields := schema.AlertRule{}.Fields()
	_ = alertruleFields
	// alertruleDescCreatedAt is the schema descriptor for created_at field.
	alertruleDescCreatedAt := alertruleMixinFields0[0].Descriptor()
	// alertrule.DefaultCreatedAt holds the default value on creation for the created_at field.
	alertrule.DefaultCreatedAt = alertruleDescCreatedAt.Default.(func() time.Time)
	// alertruleDescUpdatedAt is the schema descriptor for updated_at field.
	alertruleDescUpdatedAt := alertruleMixinFields0[1].Descriptor()
	// alertrule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	alertrule.DefaultUpdatedAt = alertruleDescUpdatedAt.Default.(func() time.Time)
	// alertrule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	alertrule.UpdateDefaultUpdatedAt = alertruleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// alertruleDescName is the schema descriptor for name field.
	alertruleDescName := alertruleFields[1].Descriptor()
	// alertrule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	alertrule.NameValidator = alertruleDescName.Validators[0].(func(string) error)
	// alertruleDescThreshold is the schema descriptor for threshold field.
	alertruleDescThreshold := alertruleFields[3].Descriptor()
	// alertrule.ThresholdValidator is a validator for the "threshold" field. It is called by the builders before save.
	alertrule.ThresholdValidator = alertruleDescThreshold.Validators[0].(func(int64) error)
	// alertruleDescEnabled is the schema descriptor for enabled field.
	alertruleDescEnabled := alertruleFields[4].Descriptor()
	// alertrule.DefaultEnabled holds the default value on creation for the enabled field.
	alertrule.DefaultEnabled = alertruleDescEnabled.Default.(bool)
	// alertruleDescDescription is the schema descriptor for description field.
	alertruleDescDescription := alertruleFields[5].Descriptor()
	// alertrule.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	alertrule.DescriptionValidator = alertruleDescDescription.Validators[0].(func(string) error)
	// alertruleDescID is the schema descriptor for id field.
	alertruleDescID := alertruleFields[0].Descriptor()
	// alertrule.DefaultID holds the default value on creation for the id field.
	alertrule.DefaultID = alertruleDescID.Default.(func() uuid.UUID)
	auditlogMixin := schema.AuditLog{}.Mixin()
	auditlogMixinFields0 := auditlogMixin[0].Fields()
	_ = auditlogMixinFields0
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogMixinFields0[0].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	// auditlogDescUpdatedAt is the schema descriptor for updated_at field.
	auditlogDescUpdatedAt := auditlogMixinFields0[1].Descriptor()
	// auditlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	auditlog.DefaultUpdatedAt = auditlogDescUpdatedAt.Default.(func() time.Time)
	// auditlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	auditlog.UpdateDefaultUpdatedAt = auditlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[3].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescTargetType is the schema descriptor for target_type field.
	auditlogDescTargetType := auditlogFields[4].Descriptor()
	// auditlog.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	auditlog.TargetTypeValidator = auditlogDescTargetType.Validators[0].(func(string) error)
	// auditlogDescDetails is the schema descriptor for details field.
	auditlogDescDetails := auditlogFields[6].Descriptor()
	// auditlog.DefaultDetails holds the default value on creation for the details field.
	auditlog.DefaultDetails = auditlogDescDetails.Default.(map[string]interface{})
	// auditlogDescIP is the schema descriptor for ip field.
	auditlogDescIP := auditlogFields[7].Descriptor()
	// auditlog.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	auditlog.IPValidator = auditlogDescIP.Validators[0].(func(string) error)
	// auditlogDescUserAgent is the schema descriptor for user_agent field.
	auditlogDescUserAgent := auditlogFields[8].Descriptor()
	// auditlog.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	auditlog.UserAgentValidator = auditlogDescUserAgent.Validators[0].(func(string) error)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	balancerecordMixin := schema.BalanceRecord{}.Mixin()
	balancerecordMixinFields0 := balancerecordMixin[0].Fields()
	_ = balancerecordMixinFields0
	balancerecordFields := schema.BalanceRecord{}.Fields()
	_ = balancerecordFields
	// balancerecordDescCreatedAt is the schema descriptor for created_at field.
	balancerecordDescCreatedAt := balancerecordMixinFields0[0].Descriptor()
	// balancerecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	balancerecord.DefaultCreatedAt = balancerecordDescCreatedAt.Default.(func() time.Time)
	// balancerecordDescUpdatedAt is the schema descriptor for updated_at field.
	balancerecordDescUpdatedAt := balancerecordMixinFields0[1].Descriptor()
	// balancerecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	balancerecord.DefaultUpdatedAt = balancerecordDescUpdatedAt.Default.(func() time.Time)
	// balancerecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	balancerecord.UpdateDefaultUpdatedAt = balancerecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// balancerecordDescBalanceAfter is the schema descriptor for balance_after field.
	balancerecordDescBalanceAfter := balancerecordFields[6].Descriptor()
	// balancerecord.DefaultBalanceAfter holds the default value on creation for the balance_after field.
	balancerecord.DefaultBalanceAfter = balancerecordDescBalanceAfter.Default.(int64)
	// balancerecordDescRemark is the schema descriptor for remark field.
	balancerecordDescRemark := balancerecordFields[7].Descriptor()
	// balancerecord.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	balancerecord.RemarkValidator = balancerecordDescRemark.Validators[0].(func(string) error)
	// balancerecordDescID is the schema descriptor for id field.
	balancerecordDescID := balancerecordFields[0].Descriptor()
	// balancerecord.DefaultID holds the default value on creation for the id field.
	balancerecord.DefaultID = balancerecordDescID.Default.(func() uuid.UUID)
	calllogMixin := schema.CallLog{}.Mixin()
	calllogMixinFields0 := calllogMixin[0].Fields()
	_ = calllogMixinFields0
	calllogFields := schema.CallLog{}.Fields()
	_ = calllogFields
	// calllogDescCreatedAt is the schema descriptor for created_at field.
	calllogDescCreatedAt := calllogMixinFields0[0].Descriptor()
	// calllog.DefaultCreatedAt holds the default value on creation for the created_at field.
	calllog.DefaultCreatedAt = calllogDescCreatedAt.Default.(func() time.Time)
	// calllogDescUpdatedAt is the schema descriptor for updated_at field.
	calllogDescUpdatedAt := calllogMixinFields0[1].Descriptor()
	// calllog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	calllog.DefaultUpdatedAt = calllogDescUpdatedAt.Default.(func() time.Time)
	// calllog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	calllog.UpdateDefaultUpdatedAt = calllogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// calllogDescModel is the schema descriptor for model field.
	calllogDescModel := calllogFields[5].Descriptor()
	// calllog.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	calllog.ModelValidator = calllogDescModel.Validators[0].(func(string) error)
	// calllogDescPromptTokens is the schema descriptor for prompt_tokens field.
	calllogDescPromptTokens := calllogFields[6].Descriptor()
	// calllog.DefaultPromptTokens holds the default value on creation for the prompt_tokens field.
	calllog.DefaultPromptTokens = calllogDescPromptTokens.Default.(int64)
	// calllogDescCompletionTokens is the schema descriptor for completion_tokens field.
	calllogDescCompletionTokens := calllogFields[7].Descriptor()
	// calllog.DefaultCompletionTokens holds the default value on creation for the completion_tokens field.
	calllog.DefaultCompletionTokens = calllogDescCompletionTokens.Default.(int64)
	// calllogDescTotalTokens is the schema descriptor for total_tokens field.
	calllogDescTotalTokens := calllogFields[8].Descriptor()
	// calllog.DefaultTotalTokens holds the default value on creation for the total_tokens field.
	calllog.DefaultTotalTokens = calllogDescTotalTokens.Default.(int64)
	// calllogDescLatencyMs is the schema descriptor for latency_ms field.
	calllogDescLatencyMs := calllogFields[9].Descriptor()
	// calllog.DefaultLatencyMs holds the default value on creation for the latency_ms field.
	calllog.DefaultLatencyMs = calllogDescLatencyMs.Default.(int64)
	// calllogDescStatusCode is the schema descriptor for status_code field.
	calllogDescStatusCode := calllogFields[10].Descriptor()
	// calllog.DefaultStatusCode holds the default value on creation for the status_code field.
	calllog.DefaultStatusCode = calllogDescStatusCode.Default.(int)
	// calllogDescErrorMsg is the schema descriptor for error_msg field.
	calllogDescErrorMsg := calllogFields[11].Descriptor()
	// calllog.ErrorMsgValidator is a validator for the "error_msg" field. It is called by the builders before save.
	calllog.ErrorMsgValidator = calllogDescErrorMsg.Validators[0].(func(string) error)
	// calllogDescID is the schema descriptor for id field.
	calllogDescID := calllogFields[0].Descriptor()
	// calllog.DefaultID holds the default value on creation for the id field.
	calllog.DefaultID = calllogDescID.Default.(func() uuid.UUID)
	departmentMixin := schema.Department{}.Mixin()
	departmentMixinFields0 := departmentMixin[0].Fields()
	_ = departmentMixinFields0
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescCreatedAt is the schema descriptor for created_at field.
	departmentDescCreatedAt := departmentMixinFields0[0].Descriptor()
	// department.DefaultCreatedAt holds the default value on creation for the created_at field.
	department.DefaultCreatedAt = departmentDescCreatedAt.Default.(func() time.Time)
	// departmentDescUpdatedAt is the schema descriptor for updated_at field.
	departmentDescUpdatedAt := departmentMixinFields0[1].Descriptor()
	// department.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	department.DefaultUpdatedAt = departmentDescUpdatedAt.Default.(func() time.Time)
	// department.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	department.UpdateDefaultUpdatedAt = departmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// departmentDescName is the schema descriptor for name field.
	departmentDescName := departmentFields[1].Descriptor()
	// department.NameValidator is a validator for the "name" field. It is called by the builders before save.
	department.NameValidator = func() func(string) error {
		validators := departmentDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// departmentDescCode is the schema descriptor for code field.
	departmentDescCode := departmentFields[2].Descriptor()
	// department.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	department.CodeValidator = func() func(string) error {
		validators := departmentDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// departmentDescLevel is the schema descriptor for level field.
	departmentDescLevel := departmentFields[4].Descriptor()
	// department.DefaultLevel holds the default value on creation for the level field.
	department.DefaultLevel = departmentDescLevel.Default.(int)
	// departmentDescPath is the schema descriptor for path field.
	departmentDescPath := departmentFields[5].Descriptor()
	// department.DefaultPath holds the default value on creation for the path field.
	department.DefaultPath = departmentDescPath.Default.(string)
	// department.PathValidator is a validator for the "path" field. It is called by the builders before save.
	department.PathValidator = departmentDescPath.Validators[0].(func(string) error)
	// departmentDescSortOrder is the schema descriptor for sort_order field.
	departmentDescSortOrder := departmentFields[6].Descriptor()
	// department.DefaultSortOrder holds the default value on creation for the sort_order field.
	department.DefaultSortOrder = departmentDescSortOrder.Default.(int)
	// departmentDescID is the schema descriptor for id field.
	departmentDescID := departmentFields[0].Descriptor()
	// department.DefaultID holds the default value on creation for the id field.
	department.DefaultID = departmentDescID.Default.(func() uuid.UUID)
	groupMixin := schema.Group{}.Mixin()
	groupMixinFields0 := groupMixin[0].Fields()
	_ = groupMixinFields0
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupMixinFields0[0].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupMixinFields0[1].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[1].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = func() func(string) error {
		validators := groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescCode is the schema descriptor for code field.
	groupDescCode := groupFields[2].Descriptor()
	// group.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	group.CodeValidator = func() func(string) error {
		validators := groupDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescDescription is the schema descriptor for description field.
	groupDescDescription := groupFields[3].Descriptor()
	// group.DefaultDescription holds the default value on creation for the description field.
	group.DefaultDescription = groupDescDescription.Default.(string)
	// group.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	group.DescriptionValidator = groupDescDescription.Validators[0].(func(string) error)
	// groupDescSortOrder is the schema descriptor for sort_order field.
	groupDescSortOrder := groupFields[4].Descriptor()
	// group.DefaultSortOrder holds the default value on creation for the sort_order field.
	group.DefaultSortOrder = groupDescSortOrder.Default.(int)
	// groupDescID is the schema descriptor for id field.
	groupDescID := groupFields[0].Descriptor()
	// group.DefaultID holds the default value on creation for the id field.
	group.DefaultID = groupDescID.Default.(func() uuid.UUID)
	groupplatformMixin := schema.GroupPlatform{}.Mixin()
	groupplatformMixinFields0 := groupplatformMixin[0].Fields()
	_ = groupplatformMixinFields0
	groupplatformFields := schema.GroupPlatform{}.Fields()
	_ = groupplatformFields
	// groupplatformDescCreatedAt is the schema descriptor for created_at field.
	groupplatformDescCreatedAt := groupplatformMixinFields0[0].Descriptor()
	// groupplatform.DefaultCreatedAt holds the default value on creation for the created_at field.
	groupplatform.DefaultCreatedAt = groupplatformDescCreatedAt.Default.(func() time.Time)
	// groupplatformDescUpdatedAt is the schema descriptor for updated_at field.
	groupplatformDescUpdatedAt := groupplatformMixinFields0[1].Descriptor()
	// groupplatform.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	groupplatform.DefaultUpdatedAt = groupplatformDescUpdatedAt.Default.(func() time.Time)
	// groupplatform.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	groupplatform.UpdateDefaultUpdatedAt = groupplatformDescUpdatedAt.UpdateDefault.(func() time.Time)
	// groupplatformDescID is the schema descriptor for id field.
	groupplatformDescID := groupplatformFields[0].Descriptor()
	// groupplatform.DefaultID holds the default value on creation for the id field.
	groupplatform.DefaultID = groupplatformDescID.Default.(func() uuid.UUID)
	guidesectionMixin := schema.GuideSection{}.Mixin()
	guidesectionMixinFields0 := guidesectionMixin[0].Fields()
	_ = guidesectionMixinFields0
	guidesectionFields := schema.GuideSection{}.Fields()
	_ = guidesectionFields
	// guidesectionDescCreatedAt is the schema descriptor for created_at field.
	guidesectionDescCreatedAt := guidesectionMixinFields0[0].Descriptor()
	// guidesection.DefaultCreatedAt holds the default value on creation for the created_at field.
	guidesection.DefaultCreatedAt = guidesectionDescCreatedAt.Default.(func() time.Time)
	// guidesectionDescUpdatedAt is the schema descriptor for updated_at field.
	guidesectionDescUpdatedAt := guidesectionMixinFields0[1].Descriptor()
	// guidesection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	guidesection.DefaultUpdatedAt = guidesectionDescUpdatedAt.Default.(func() time.Time)
	// guidesection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	guidesection.UpdateDefaultUpdatedAt = guidesectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// guidesectionDescTitle is the schema descriptor for title field.
	guidesectionDescTitle := guidesectionFields[1].Descriptor()
	// guidesection.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	guidesection.TitleValidator = func() func(string) error {
		validators := guidesectionDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// guidesectionDescContentMd is the schema descriptor for content_md field.
	guidesectionDescContentMd := guidesectionFields[2].Descriptor()
	// guidesection.ContentMdValidator is a validator for the "content_md" field. It is called by the builders before save.
	guidesection.ContentMdValidator = guidesectionDescContentMd.Validators[0].(func(string) error)
	// guidesectionDescSortOrder is the schema descriptor for sort_order field.
	guidesectionDescSortOrder := guidesectionFields[4].Descriptor()
	// guidesection.DefaultSortOrder holds the default value on creation for the sort_order field.
	guidesection.DefaultSortOrder = guidesectionDescSortOrder.Default.(int)
	// guidesectionDescIsEnabled is the schema descriptor for is_enabled field.
	guidesectionDescIsEnabled := guidesectionFields[5].Descriptor()
	// guidesection.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	guidesection.DefaultIsEnabled = guidesectionDescIsEnabled.Default.(bool)
	// guidesectionDescID is the schema descriptor for id field.
	guidesectionDescID := guidesectionFields[0].Descriptor()
	// guidesection.DefaultID holds the default value on creation for the id field.
	guidesection.DefaultID = guidesectionDescID.Default.(func() uuid.UUID)
	notificationMixin := schema.Notification{}.Mixin()
	notificationMixinFields0 := notificationMixin[0].Fields()
	_ = notificationMixinFields0
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationMixinFields0[0].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	// notificationDescUpdatedAt is the schema descriptor for updated_at field.
	notificationDescUpdatedAt := notificationMixinFields0[1].Descriptor()
	// notification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notification.DefaultUpdatedAt = notificationDescUpdatedAt.Default.(func() time.Time)
	// notification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notification.UpdateDefaultUpdatedAt = notificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notificationDescTitle is the schema descriptor for title field.
	notificationDescTitle := notificationFields[3].Descriptor()
	// notification.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	notification.TitleValidator = notificationDescTitle.Validators[0].(func(string) error)
	// notificationDescContent is the schema descriptor for content field.
	notificationDescContent := notificationFields[4].Descriptor()
	// notification.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	notification.ContentValidator = notificationDescContent.Validators[0].(func(string) error)
	// notificationDescIsRead is the schema descriptor for is_read field.
	notificationDescIsRead := notificationFields[5].Descriptor()
	// notification.DefaultIsRead holds the default value on creation for the is_read field.
	notification.DefaultIsRead = notificationDescIsRead.Default.(bool)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.DefaultID holds the default value on creation for the id field.
	notification.DefaultID = notificationDescID.Default.(func() uuid.UUID)
	notificationreadFields := schema.NotificationRead{}.Fields()
	_ = notificationreadFields
	// notificationreadDescReadAt is the schema descriptor for read_at field.
	notificationreadDescReadAt := notificationreadFields[3].Descriptor()
	// notificationread.DefaultReadAt holds the default value on creation for the read_at field.
	notificationread.DefaultReadAt = notificationreadDescReadAt.Default.(func() time.Time)
	// notificationreadDescID is the schema descriptor for id field.
	notificationreadDescID := notificationreadFields[0].Descriptor()
	// notificationread.DefaultID holds the default value on creation for the id field.
	notificationread.DefaultID = notificationreadDescID.Default.(func() uuid.UUID)
	platformMixin := schema.Platform{}.Mixin()
	platformMixinFields0 := platformMixin[0].Fields()
	_ = platformMixinFields0
	platformFields := schema.Platform{}.Fields()
	_ = platformFields
	// platformDescCreatedAt is the schema descriptor for created_at field.
	platformDescCreatedAt := platformMixinFields0[0].Descriptor()
	// platform.DefaultCreatedAt holds the default value on creation for the created_at field.
	platform.DefaultCreatedAt = platformDescCreatedAt.Default.(func() time.Time)
	// platformDescUpdatedAt is the schema descriptor for updated_at field.
	platformDescUpdatedAt := platformMixinFields0[1].Descriptor()
	// platform.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	platform.DefaultUpdatedAt = platformDescUpdatedAt.Default.(func() time.Time)
	// platform.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	platform.UpdateDefaultUpdatedAt = platformDescUpdatedAt.UpdateDefault.(func() time.Time)
	// platformDescName is the schema descriptor for name field.
	platformDescName := platformFields[1].Descriptor()
	// platform.NameValidator is a validator for the "name" field. It is called by the builders before save.
	platform.NameValidator = func() func(string) error {
		validators := platformDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// platformDescCode is the schema descriptor for code field.
	platformDescCode := platformFields[2].Descriptor()
	// platform.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	platform.CodeValidator = func() func(string) error {
		validators := platformDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// platformDescBaseURL is the schema descriptor for base_url field.
	platformDescBaseURL := platformFields[4].Descriptor()
	// platform.BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	platform.BaseURLValidator = func() func(string) error {
		validators := platformDescBaseURL.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(base_url string) error {
			for _, fn := range fns {
				if err := fn(base_url); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// platformDescID is the schema descriptor for id field.
	platformDescID := platformFields[0].Descriptor()
	// platform.DefaultID holds the default value on creation for the id field.
	platform.DefaultID = platformDescID.Default.(func() uuid.UUID)
	quotarecordMixin := schema.QuotaRecord{}.Mixin()
	quotarecordMixinFields0 := quotarecordMixin[0].Fields()
	_ = quotarecordMixinFields0
	quotarecordFields := schema.QuotaRecord{}.Fields()
	_ = quotarecordFields
	// quotarecordDescCreatedAt is the schema descriptor for created_at field.
	quotarecordDescCreatedAt := quotarecordMixinFields0[0].Descriptor()
	// quotarecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	quotarecord.DefaultCreatedAt = quotarecordDescCreatedAt.Default.(func() time.Time)
	// quotarecordDescUpdatedAt is the schema descriptor for updated_at field.
	quotarecordDescUpdatedAt := quotarecordMixinFields0[1].Descriptor()
	// quotarecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	quotarecord.DefaultUpdatedAt = quotarecordDescUpdatedAt.Default.(func() time.Time)
	// quotarecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	quotarecord.UpdateDefaultUpdatedAt = quotarecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// quotarecordDescAmount is the schema descriptor for amount field.
	quotarecordDescAmount := quotarecordFields[5].Descriptor()
	// quotarecord.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	quotarecord.AmountValidator = quotarecordDescAmount.Validators[0].(func(int64) error)
	// quotarecordDescQuotaAfter is the schema descriptor for quota_after field.
	quotarecordDescQuotaAfter := quotarecordFields[6].Descriptor()
	// quotarecord.DefaultQuotaAfter holds the default value on creation for the quota_after field.
	quotarecord.DefaultQuotaAfter = quotarecordDescQuotaAfter.Default.(int64)
	// quotarecordDescID is the schema descriptor for id field.
	quotarecordDescID := quotarecordFields[0].Descriptor()
	// quotarecord.DefaultID holds the default value on creation for the id field.
	quotarecord.DefaultID = quotarecordDescID.Default.(func() uuid.UUID)
	quotarequestMixin := schema.QuotaRequest{}.Mixin()
	quotarequestMixinFields0 := quotarequestMixin[0].Fields()
	_ = quotarequestMixinFields0
	quotarequestFields := schema.QuotaRequest{}.Fields()
	_ = quotarequestFields
	// quotarequestDescCreatedAt is the schema descriptor for created_at field.
	quotarequestDescCreatedAt := quotarequestMixinFields0[0].Descriptor()
	// quotarequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	quotarequest.DefaultCreatedAt = quotarequestDescCreatedAt.Default.(func() time.Time)
	// quotarequestDescUpdatedAt is the schema descriptor for updated_at field.
	quotarequestDescUpdatedAt := quotarequestMixinFields0[1].Descriptor()
	// quotarequest.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	quotarequest.DefaultUpdatedAt = quotarequestDescUpdatedAt.Default.(func() time.Time)
	// quotarequest.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	quotarequest.UpdateDefaultUpdatedAt = quotarequestDescUpdatedAt.UpdateDefault.(func() time.Time)
	// quotarequestDescRequestedAmount is the schema descriptor for requested_amount field.
	quotarequestDescRequestedAmount := quotarequestFields[3].Descriptor()
	// quotarequest.RequestedAmountValidator is a validator for the "requested_amount" field. It is called by the builders before save.
	quotarequest.RequestedAmountValidator = quotarequestDescRequestedAmount.Validators[0].(func(int64) error)
	// quotarequestDescReason is the schema descriptor for reason field.
	quotarequestDescReason := quotarequestFields[4].Descriptor()
	// quotarequest.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	quotarequest.ReasonValidator = quotarequestDescReason.Validators[0].(func(string) error)
	// quotarequestDescID is the schema descriptor for id field.
	quotarequestDescID := quotarequestFields[0].Descriptor()
	// quotarequest.DefaultID holds the default value on creation for the id field.
	quotarequest.DefaultID = quotarequestDescID.Default.(func() uuid.UUID)
	rechargeorderMixin := schema.RechargeOrder{}.Mixin()
	rechargeorderMixinFields0 := rechargeorderMixin[0].Fields()
	_ = rechargeorderMixinFields0
	rechargeorderFields := schema.RechargeOrder{}.Fields()
	_ = rechargeorderFields
	// rechargeorderDescCreatedAt is the schema descriptor for created_at field.
	rechargeorderDescCreatedAt := rechargeorderMixinFields0[0].Descriptor()
	// rechargeorder.DefaultCreatedAt holds the default value on creation for the created_at field.
	rechargeorder.DefaultCreatedAt = rechargeorderDescCreatedAt.Default.(func() time.Time)
	// rechargeorderDescUpdatedAt is the schema descriptor for updated_at field.
	rechargeorderDescUpdatedAt := rechargeorderMixinFields0[1].Descriptor()
	// rechargeorder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rechargeorder.DefaultUpdatedAt = rechargeorderDescUpdatedAt.Default.(func() time.Time)
	// rechargeorder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rechargeorder.UpdateDefaultUpdatedAt = rechargeorderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rechargeorderDescAmount is the schema descriptor for amount field.
	rechargeorderDescAmount := rechargeorderFields[2].Descriptor()
	// rechargeorder.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	rechargeorder.AmountValidator = rechargeorderDescAmount.Validators[0].(func(int64) error)
	// rechargeorderDescProviderOrderID is the schema descriptor for provider_order_id field.
	rechargeorderDescProviderOrderID := rechargeorderFields[5].Descriptor()
	// rechargeorder.ProviderOrderIDValidator is a validator for the "provider_order_id" field. It is called by the builders before save.
	rechargeorder.ProviderOrderIDValidator = rechargeorderDescProviderOrderID.Validators[0].(func(string) error)
	// rechargeorderDescRefundedAmount is the schema descriptor for refunded_amount field.
	rechargeorderDescRefundedAmount := rechargeorderFields[7].Descriptor()
	// rechargeorder.DefaultRefundedAmount holds the default value on creation for the refunded_amount field.
	rechargeorder.DefaultRefundedAmount = rechargeorderDescRefundedAmount.Default.(int64)
	// rechargeorderDescID is the schema descriptor for id field.
	rechargeorderDescID := rechargeorderFields[0].Descriptor()
	// rechargeorder.DefaultID holds the default value on creation for the id field.
	rechargeorder.DefaultID = rechargeorderDescID.Default.(func() uuid.UUID)
	refundrequestMixin := schema.RefundRequest{}.Mixin()
	refundrequestMixinFields0 := refundrequestMixin[0].Fields()
	_ = refundrequestMixinFields0
	refundrequestFields := schema.RefundRequest{}.Fields()
	_ = refundrequestFields
	// refundrequestDescCreatedAt is the schema descriptor for created_at field.
	refundrequestDescCreatedAt := refundrequestMixinFields0[0].Descriptor()
	// refundrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	refundrequest.DefaultCreatedAt = refundrequestDescCreatedAt.Default.(func() time.Time)
	// refundrequestDescUpdatedAt is the schema descriptor for updated_at field.
	refundrequestDescUpdatedAt := refundrequestMixinFields0[1].Descriptor()
	// refundrequest.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refundrequest.DefaultUpdatedAt = refundrequestDescUpdatedAt.Default.(func() time.Time)
	// refundrequest.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refundrequest.UpdateDefaultUpdatedAt = refundrequestDescUpdatedAt.UpdateDefault.(func() time.Time)
	// refundrequestDescAmount is the schema descriptor for amount field.
	refundrequestDescAmount := refundrequestFields[3].Descriptor()
	// refundrequest.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	refundrequest.AmountValidator = refundrequestDescAmount.Validators[0].(func(int64) error)
	// refundrequestDescReason is the schema descriptor for reason field.
	refundrequestDescReason := refundrequestFields[4].Descriptor()
	// refundrequest.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	refundrequest.ReasonValidator = refundrequestDescReason.Validators[0].(func(string) error)
	// refundrequestDescID is the schema descriptor for id field.
	refundrequestDescID := refundrequestFields[0].Descriptor()
	// refundrequest.DefaultID holds the default value on creation for the id field.
	refundrequest.DefaultID = refundrequestDescID.Default.(func() uuid.UUID)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinFields0 := settingMixin[0].Fields()
	_ = settingMixinFields0
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingMixinFields0[0].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingMixinFields0[1].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[1].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = func() func(string) error {
		validators := settingDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// settingDescValue is the schema descriptor for value field.
	settingDescValue := settingFields[2].Descriptor()
	// setting.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	setting.ValueValidator = settingDescValue.Validators[0].(func(string) error)
	// settingDescDescription is the schema descriptor for description field.
	settingDescDescription := settingFields[4].Descriptor()
	// setting.DefaultDescription holds the default value on creation for the description field.
	setting.DefaultDescription = settingDescDescription.Default.(string)
	// setting.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	setting.DescriptionValidator = settingDescDescription.Validators[0].(func(string) error)
	// settingDescIsPublic is the schema descriptor for is_public field.
	settingDescIsPublic := settingFields[5].Descriptor()
	// setting.DefaultIsPublic holds the default value on creation for the is_public field.
	setting.DefaultIsPublic = settingDescIsPublic.Default.(bool)
	// settingDescID is the schema descriptor for id field.
	settingDescID := settingFields[0].Descriptor()
	// setting.DefaultID holds the default value on creation for the id field.
	setting.DefaultID = settingDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[3].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[4].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[5].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[6].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[7].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = userDescPhone.Validators[0].(func(string) error)
	// userDescGender is the schema descriptor for gender field.
	userDescGender := userFields[9].Descriptor()
	// user.GenderValidator is a validator for the "gender" field. It is called by the builders before save.
	user.GenderValidator = userDescGender.Validators[0].(func(string) error)
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[11].Descriptor()
	// user.DefaultBalance holds the default value on creation for the balance field.
	user.DefaultBalance = userDescBalance.Default.(int64)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	usertokenMixin := schema.UserToken{}.Mixin()
	usertokenMixinFields0 := usertokenMixin[0].Fields()
	_ = usertokenMixinFields0
	usertokenFields := schema.UserToken{}.Fields()
	_ = usertokenFields
	// usertokenDescCreatedAt is the schema descriptor for created_at field.
	usertokenDescCreatedAt := usertokenMixinFields0[0].Descriptor()
	// usertoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	usertoken.DefaultCreatedAt = usertokenDescCreatedAt.Default.(func() time.Time)
	// usertokenDescUpdatedAt is the schema descriptor for updated_at field.
	usertokenDescUpdatedAt := usertokenMixinFields0[1].Descriptor()
	// usertoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usertoken.DefaultUpdatedAt = usertokenDescUpdatedAt.Default.(func() time.Time)
	// usertoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usertoken.UpdateDefaultUpdatedAt = usertokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// usertokenDescName is the schema descriptor for name field.
	usertokenDescName := usertokenFields[2].Descriptor()
	// usertoken.NameValidator is a validator for the "name" field. It is called by the builders before save.
	usertoken.NameValidator = func() func(string) error {
		validators := usertokenDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usertokenDescTokenHash is the schema descriptor for token_hash field.
	usertokenDescTokenHash := usertokenFields[3].Descriptor()
	// usertoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	usertoken.TokenHashValidator = func() func(string) error {
		validators := usertokenDescTokenHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token_hash string) error {
			for _, fn := range fns {
				if err := fn(token_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usertokenDescTokenLast4 is the schema descriptor for token_last4 field.
	usertokenDescTokenLast4 := usertokenFields[4].Descriptor()
	// usertoken.TokenLast4Validator is a validator for the "token_last4" field. It is called by the builders before save.
	usertoken.TokenLast4Validator = func() func(string) error {
		validators := usertokenDescTokenLast4.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token_last4 string) error {
			for _, fn := range fns {
				if err := fn(token_last4); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usertokenDescAPIKeyCipher is the schema descriptor for api_key_cipher field.
	usertokenDescAPIKeyCipher := usertokenFields[5].Descriptor()
	// usertoken.APIKeyCipherValidator is a validator for the "api_key_cipher" field. It is called by the builders before save.
	usertoken.APIKeyCipherValidator = usertokenDescAPIKeyCipher.Validators[0].(func(string) error)
	// usertokenDescQuotaUsed is the schema descriptor for quota_used field.
	usertokenDescQuotaUsed := usertokenFields[7].Descriptor()
	// usertoken.DefaultQuotaUsed holds the default value on creation for the quota_used field.
	usertoken.DefaultQuotaUsed = usertokenDescQuotaUsed.Default.(int64)
	// usertokenDescIsEnabled is the schema descriptor for is_enabled field.
	usertokenDescIsEnabled := usertokenFields[9].Descriptor()
	// usertoken.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	usertoken.DefaultIsEnabled = usertokenDescIsEnabled.Default.(bool)
	// usertokenDescID is the schema descriptor for id field.
	usertokenDescID := usertokenFields[0].Descriptor()
	// usertoken.DefaultID holds the default value on creation for the id field.
	usertoken.DefaultID = usertokenDescID.Default.(func() uuid.UUID)
}
