// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/predicate"
	"github.com/school-api/school-api-v1/ent/user"
	"github.com/school-api/school-api-v1/ent/usertoken"
)

// UserTokenUpdate is the builder for updating UserToken entities.
type UserTokenUpdate struct {
	config
	hooks    []Hook
	mutation *UserTokenMutation
}

// Where appends a list predicates to the UserTokenUpdate builder.
func (_u *UserTokenUpdate) Where(ps ...predicate.UserToken) *UserTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserTokenUpdate) SetUpdatedAt(v time.Time) *UserTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserTokenUpdate) SetUserID(v uuid.UUID) *UserTokenUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableUserID(v *uuid.UUID) *UserTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserTokenUpdate) SetName(v string) *UserTokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableName(v *string) *UserTokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *UserTokenUpdate) SetTokenHash(v string) *UserTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableTokenHash(v *string) *UserTokenUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetTokenLast4 sets the "token_last4" field.
func (_u *UserTokenUpdate) SetTokenLast4(v string) *UserTokenUpdate {
	_u.mutation.SetTokenLast4(v)
	return _u
}

// SetNillableTokenLast4 sets the "token_last4" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableTokenLast4(v *string) *UserTokenUpdate {
	if v != nil {
		_u.SetTokenLast4(*v)
	}
	return _u
}

// SetAPIKeyCipher sets the "api_key_cipher" field.
func (_u *UserTokenUpdate) SetAPIKeyCipher(v string) *UserTokenUpdate {
	_u.mutation.SetAPIKeyCipher(v)
	return _u
}

// SetNillableAPIKeyCipher sets the "api_key_cipher" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableAPIKeyCipher(v *string) *UserTokenUpdate {
	if v != nil {
		_u.SetAPIKeyCipher(*v)
	}
	return _u
}

// ClearAPIKeyCipher clears the value of the "api_key_cipher" field.
func (_u *UserTokenUpdate) ClearAPIKeyCipher() *UserTokenUpdate {
	_u.mutation.ClearAPIKeyCipher()
	return _u
}

// SetQuotaLimit sets the "quota_limit" field.
func (_u *UserTokenUpdate) SetQuotaLimit(v int64) *UserTokenUpdate {
	_u.mutation.ResetQuotaLimit()
	_u.mutation.SetQuotaLimit(v)
	return _u
}

// SetNillableQuotaLimit sets the "quota_limit" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableQuotaLimit(v *int64) *UserTokenUpdate {
	if v != nil {
		_u.SetQuotaLimit(*v)
	}
	return _u
}

// AddQuotaLimit adds value to the "quota_limit" field.
func (_u *UserTokenUpdate) AddQuotaLimit(v int64) *UserTokenUpdate {
	_u.mutation.AddQuotaLimit(v)
	return _u
}

// ClearQuotaLimit clears the value of the "quota_limit" field.
func (_u *UserTokenUpdate) ClearQuotaLimit() *UserTokenUpdate {
	_u.mutation.ClearQuotaLimit()
	return _u
}

// SetQuotaUsed sets the "quota_used" field.
func (_u *UserTokenUpdate) SetQuotaUsed(v int64) *UserTokenUpdate {
	_u.mutation.ResetQuotaUsed()
	_u.mutation.SetQuotaUsed(v)
	return _u
}

// SetNillableQuotaUsed sets the "quota_used" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableQuotaUsed(v *int64) *UserTokenUpdate {
	if v != nil {
		_u.SetQuotaUsed(*v)
	}
	return _u
}

// AddQuotaUsed adds value to the "quota_used" field.
func (_u *UserTokenUpdate) AddQuotaUsed(v int64) *UserTokenUpdate {
	_u.mutation.AddQuotaUsed(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserTokenUpdate) SetExpiresAt(v time.Time) *UserTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableExpiresAt(v *time.Time) *UserTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserTokenUpdate) ClearExpiresAt() *UserTokenUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *UserTokenUpdate) SetIsEnabled(v bool) *UserTokenUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableIsEnabled(v *bool) *UserTokenUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserTokenUpdate) SetUser(v *User) *UserTokenUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserTokenMutation object of the builder.
func (_u *UserTokenUpdate) Mutation() *UserTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserTokenUpdate) ClearUser() *UserTokenUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usertoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTokenUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := usertoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserToken.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := usertoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "UserToken.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenLast4(); ok {
		if err := usertoken.TokenLast4Validator(v); err != nil {
			return &ValidationError{Name: "token_last4", err: fmt.Errorf(`ent: validator failed for field "UserToken.token_last4": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyCipher(); ok {
		if err := usertoken.APIKeyCipherValidator(v); err != nil {
			return &ValidationError{Name: "api_key_cipher", err: fmt.Errorf(`ent: validator failed for field "UserToken.api_key_cipher": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserToken.user"`)
	}
	return nil
}

func (_u *UserTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertoken.Table, usertoken.Columns, sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usertoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(usertoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(usertoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenLast4(); ok {
		_spec.SetField(usertoken.FieldTokenLast4, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyCipher(); ok {
		_spec.SetField(usertoken.FieldAPIKeyCipher, field.TypeString, value)
	}
	if _u.mutation.APIKeyCipherCleared() {
		_spec.ClearField(usertoken.FieldAPIKeyCipher, field.TypeString)
	}
	if value, ok := _u.mutation.QuotaLimit(); ok {
		_spec.SetField(usertoken.FieldQuotaLimit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaLimit(); ok {
		_spec.AddField(usertoken.FieldQuotaLimit, field.TypeInt64, value)
	}
	if _u.mutation.QuotaLimitCleared() {
		_spec.ClearField(usertoken.FieldQuotaLimit, field.TypeInt64)
	}
	if value, ok := _u.mutation.QuotaUsed(); ok {
		_spec.SetField(usertoken.FieldQuotaUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsed(); ok {
		_spec.AddField(usertoken.FieldQuotaUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usertoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(usertoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(usertoken.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertoken.UserTable,
			Columns: []string{usertoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertoken.UserTable,
			Columns: []string{usertoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserTokenUpdateOne is the builder for updating a single UserToken entity.
type UserTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserTokenMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserTokenUpdateOne) SetUpdatedAt(v time.Time) *UserTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserTokenUpdateOne) SetUserID(v uuid.UUID) *UserTokenUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableUserID(v *uuid.UUID) *UserTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserTokenUpdateOne) SetName(v string) *UserTokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableName(v *string) *UserTokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *UserTokenUpdateOne) SetTokenHash(v string) *UserTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableTokenHash(v *string) *UserTokenUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetTokenLast4 sets the "token_last4" field.
func (_u *UserTokenUpdateOne) SetTokenLast4(v string) *UserTokenUpdateOne {
	_u.mutation.SetTokenLast4(v)
	return _u
}

// SetNillableTokenLast4 sets the "token_last4" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableTokenLast4(v *string) *UserTokenUpdateOne {
	if v != nil {
		_u.SetTokenLast4(*v)
	}
	return _u
}

// SetAPIKeyCipher sets the "api_key_cipher" field.
func (_u *UserTokenUpdateOne) SetAPIKeyCipher(v string) *UserTokenUpdateOne {
	_u.mutation.SetAPIKeyCipher(v)
	return _u
}

// SetNillableAPIKeyCipher sets the "api_key_cipher" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableAPIKeyCipher(v *string) *UserTokenUpdateOne {
	if v != nil {
		_u.SetAPIKeyCipher(*v)
	}
	return _u
}

// ClearAPIKeyCipher clears the value of the "api_key_cipher" field.
func (_u *UserTokenUpdateOne) ClearAPIKeyCipher() *UserTokenUpdateOne {
	_u.mutation.ClearAPIKeyCipher()
	return _u
}

// SetQuotaLimit sets the "quota_limit" field.
func (_u *UserTokenUpdateOne) SetQuotaLimit(v int64) *UserTokenUpdateOne {
	_u.mutation.ResetQuotaLimit()
	_u.mutation.SetQuotaLimit(v)
	return _u
}

// SetNillableQuotaLimit sets the "quota_limit" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableQuotaLimit(v *int64) *UserTokenUpdateOne {
	if v != nil {
		_u.SetQuotaLimit(*v)
	}
	return _u
}

// AddQuotaLimit adds value to the "quota_limit" field.
func (_u *UserTokenUpdateOne) AddQuotaLimit(v int64) *UserTokenUpdateOne {
	_u.mutation.AddQuotaLimit(v)
	return _u
}

// ClearQuotaLimit clears the value of the "quota_limit" field.
func (_u *UserTokenUpdateOne) ClearQuotaLimit() *UserTokenUpdateOne {
	_u.mutation.ClearQuotaLimit()
	return _u
}

// SetQuotaUsed sets the "quota_used" field.
func (_u *UserTokenUpdateOne) SetQuotaUsed(v int64) *UserTokenUpdateOne {
	_u.mutation.ResetQuotaUsed()
	_u.mutation.SetQuotaUsed(v)
	return _u
}

// SetNillableQuotaUsed sets the "quota_used" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableQuotaUsed(v *int64) *UserTokenUpdateOne {
	if v != nil {
		_u.SetQuotaUsed(*v)
	}
	return _u
}

// AddQuotaUsed adds value to the "quota_used" field.
func (_u *UserTokenUpdateOne) AddQuotaUsed(v int64) *UserTokenUpdateOne {
	_u.mutation.AddQuotaUsed(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserTokenUpdateOne) SetExpiresAt(v time.Time) *UserTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *UserTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserTokenUpdateOne) ClearExpiresAt() *UserTokenUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *UserTokenUpdateOne) SetIsEnabled(v bool) *UserTokenUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableIsEnabled(v *bool) *UserTokenUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserTokenUpdateOne) SetUser(v *User) *UserTokenUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserTokenMutation object of the builder.
func (_u *UserTokenUpdateOne) Mutation() *UserTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserTokenUpdateOne) ClearUser() *UserTokenUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserTokenUpdate builder.
func (_u *UserTokenUpdateOne) Where(ps ...predicate.UserToken) *UserTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserTokenUpdateOne) Select(field string, fields ...string) *UserTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserToken entity.
func (_u *UserTokenUpdateOne) Save(ctx context.Context) (*UserToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTokenUpdateOne) SaveX(ctx context.Context) *UserToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usertoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := usertoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserToken.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := usertoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "UserToken.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenLast4(); ok {
		if err := usertoken.TokenLast4Validator(v); err != nil {
			return &ValidationError{Name: "token_last4", err: fmt.Errorf(`ent: validator failed for field "UserToken.token_last4": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyCipher(); ok {
		if err := usertoken.APIKeyCipherValidator(v); err != nil {
			return &ValidationError{Name: "api_key_cipher", err: fmt.Errorf(`ent: validator failed for field "UserToken.api_key_cipher": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserToken.user"`)
	}
	return nil
}

func (_u *UserTokenUpdateOne) sqlSave(ctx context.Context) (_node *UserToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertoken.Table, usertoken.Columns, sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertoken.FieldID)
		for _, f := range fields {
			if !usertoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usertoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usertoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(usertoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(usertoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenLast4(); ok {
		_spec.SetField(usertoken.FieldTokenLast4, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyCipher(); ok {
		_spec.SetField(usertoken.FieldAPIKeyCipher, field.TypeString, value)
	}
	if _u.mutation.APIKeyCipherCleared() {
		_spec.ClearField(usertoken.FieldAPIKeyCipher, field.TypeString)
	}
	if value, ok := _u.mutation.QuotaLimit(); ok {
		_spec.SetField(usertoken.FieldQuotaLimit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaLimit(); ok {
		_spec.AddField(usertoken.FieldQuotaLimit, field.TypeInt64, value)
	}
	if _u.mutation.QuotaLimitCleared() {
		_spec.ClearField(usertoken.FieldQuotaLimit, field.TypeInt64)
	}
	if value, ok := _u.mutation.QuotaUsed(); ok {
		_spec.SetField(usertoken.FieldQuotaUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsed(); ok {
		_spec.AddField(usertoken.FieldQuotaUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usertoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(usertoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(usertoken.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertoken.UserTable,
			Columns: []string{usertoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertoken.UserTable,
			Columns: []string{usertoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
