// Code generated by ent, DO NOT EDIT.

package alertrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the alertrecord type in the database.
	Label = "alert_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// FieldMetric holds the string denoting the metric field in the database.
	FieldMetric = "metric"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTokenID holds the string denoting the token_id field in the database.
	FieldTokenID = "token_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldTriggeredValue holds the string denoting the triggered_value field in the database.
	FieldTriggeredValue = "triggered_value"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldIsResolved holds the string denoting the is_resolved field in the database.
	FieldIsResolved = "is_resolved"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldResolvedBy holds the string denoting the resolved_by field in the database.
	FieldResolvedBy = "resolved_by"
	// EdgeRule holds the string denoting the rule edge name in mutations.
	EdgeRule = "rule"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeToken holds the string denoting the token edge name in mutations.
	EdgeToken = "token"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeResolver holds the string denoting the resolver edge name in mutations.
	EdgeResolver = "resolver"
	// Table holds the table name of the alertrecord in the database.
	Table = "alert_records"
	// RuleTable is the table that holds the rule relation/edge.
	RuleTable = "alert_records"
	// RuleInverseTable is the table name for the AlertRule entity.
	// It exists in this package in order to avoid circular dependency with the "alertrule" package.
	RuleInverseTable = "alert_rules"
	// RuleColumn is the table column denoting the rule relation/edge.
	RuleColumn = "rule_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "alert_records"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// TokenTable is the table that holds the token relation/edge.
	TokenTable = "alert_records"
	// TokenInverseTable is the table name for the UserToken entity.
	// It exists in this package in order to avoid circular dependency with the "usertoken" package.
	TokenInverseTable = "user_tokens"
	// TokenColumn is the table column denoting the token relation/edge.
	TokenColumn = "token_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "alert_records"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
	// ResolverTable is the table that holds the resolver relation/edge.
	ResolverTable = "alert_records"
	// ResolverInverseTable is the table name for the AdminUser entity.
	// It exists in this package in order to avoid circular dependency with the "adminuser" package.
	ResolverInverseTable = "admin_users"
	// ResolverColumn is the table column denoting the resolver relation/edge.
	ResolverColumn = "resolved_by"
)

// Columns holds all SQL columns for alertrecord fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRuleID,
	FieldMetric,
	FieldUserID,
	FieldTokenID,
	FieldAccountID,
	FieldTriggeredValue,
	FieldMessage,
	FieldIsResolved,
	FieldResolvedAt,
	FieldResolvedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// MetricValidator is a validator for the "metric" field. It is called by the builders before save.
	MetricValidator func(string) error
	// DefaultTriggeredValue holds the default value on creation for the "triggered_value" field.
	DefaultTriggeredValue int64
	// MessageValidator is a validator for the "message" field. It is called by the builders before save.
	MessageValidator func(string) error
	// DefaultIsResolved holds the default value on creation for the "is_resolved" field.
	DefaultIsResolved bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AlertRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// ByMetric orders the results by the metric field.
func ByMetric(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetric, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByTokenID orders the results by the token_id field.
func ByTokenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByTriggeredValue orders the results by the triggered_value field.
func ByTriggeredValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggeredValue, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByIsResolved orders the results by the is_resolved field.
func ByIsResolved(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsResolved, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByResolvedBy orders the results by the resolved_by field.
func ByResolvedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedBy, opts...).ToFunc()
}

// ByRuleField orders the results by rule field.
func ByRuleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRuleStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByTokenField orders the results by token field.
func ByTokenField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTokenStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByResolverField orders the results by resolver field.
func ByResolverField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResolverStep(), sql.OrderByField(field, opts...))
	}
}
func newRuleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RuleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RuleTable, RuleColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
func newTokenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TokenInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TokenTable, TokenColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
	)
}
func newResolverStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResolverInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ResolverTable, ResolverColumn),
	)
}
