// Code generated by ent, DO NOT EDIT.

package alertrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/school-api/school-api-v1/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldRuleID, v))
}

// Metric applies equality check predicate on the "metric" field. It's identical to MetricEQ.
func Metric(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldMetric, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldUserID, v))
}

// TokenID applies equality check predicate on the "token_id" field. It's identical to TokenIDEQ.
func TokenID(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldTokenID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldAccountID, v))
}

// TriggeredValue applies equality check predicate on the "triggered_value" field. It's identical to TriggeredValueEQ.
func TriggeredValue(v int64) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldTriggeredValue, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldMessage, v))
}

// IsResolved applies equality check predicate on the "is_resolved" field. It's identical to IsResolvedEQ.
func IsResolved(v bool) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldIsResolved, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedBy applies equality check predicate on the "resolved_by" field. It's identical to ResolvedByEQ.
func ResolvedBy(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldResolvedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldRuleID, vs...))
}

// RuleIDIsNil applies the IsNil predicate on the "rule_id" field.
func RuleIDIsNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIsNull(FieldRuleID))
}

// RuleIDNotNil applies the NotNil predicate on the "rule_id" field.
func RuleIDNotNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotNull(FieldRuleID))
}

// MetricEQ applies the EQ predicate on the "metric" field.
func MetricEQ(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldMetric, v))
}

// MetricNEQ applies the NEQ predicate on the "metric" field.
func MetricNEQ(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldMetric, v))
}

// MetricIn applies the In predicate on the "metric" field.
func MetricIn(vs ...string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldMetric, vs...))
}

// MetricNotIn applies the NotIn predicate on the "metric" field.
func MetricNotIn(vs ...string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldMetric, vs...))
}

// MetricGT applies the GT predicate on the "metric" field.
func MetricGT(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGT(FieldMetric, v))
}

// MetricGTE applies the GTE predicate on the "metric" field.
func MetricGTE(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGTE(FieldMetric, v))
}

// MetricLT applies the LT predicate on the "metric" field.
func MetricLT(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLT(FieldMetric, v))
}

// MetricLTE applies the LTE predicate on the "metric" field.
func MetricLTE(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLTE(FieldMetric, v))
}

// MetricContains applies the Contains predicate on the "metric" field.
func MetricContains(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldContains(FieldMetric, v))
}

// MetricHasPrefix applies the HasPrefix predicate on the "metric" field.
func MetricHasPrefix(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldHasPrefix(FieldMetric, v))
}

// MetricHasSuffix applies the HasSuffix predicate on the "metric" field.
func MetricHasSuffix(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldHasSuffix(FieldMetric, v))
}

// MetricEqualFold applies the EqualFold predicate on the "metric" field.
func MetricEqualFold(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEqualFold(FieldMetric, v))
}

// MetricContainsFold applies the ContainsFold predicate on the "metric" field.
func MetricContainsFold(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldContainsFold(FieldMetric, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotNull(FieldUserID))
}

// TokenIDEQ applies the EQ predicate on the "token_id" field.
func TokenIDEQ(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldTokenID, v))
}

// TokenIDNEQ applies the NEQ predicate on the "token_id" field.
func TokenIDNEQ(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldTokenID, v))
}

// TokenIDIn applies the In predicate on the "token_id" field.
func TokenIDIn(vs ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldTokenID, vs...))
}

// TokenIDNotIn applies the NotIn predicate on the "token_id" field.
func TokenIDNotIn(vs ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldTokenID, vs...))
}

// TokenIDIsNil applies the IsNil predicate on the "token_id" field.
func TokenIDIsNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIsNull(FieldTokenID))
}

// TokenIDNotNil applies the NotNil predicate on the "token_id" field.
func TokenIDNotNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotNull(FieldTokenID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotNull(FieldAccountID))
}

// TriggeredValueEQ applies the EQ predicate on the "triggered_value" field.
func TriggeredValueEQ(v int64) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldTriggeredValue, v))
}

// TriggeredValueNEQ applies the NEQ predicate on the "triggered_value" field.
func TriggeredValueNEQ(v int64) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldTriggeredValue, v))
}

// TriggeredValueIn applies the In predicate on the "triggered_value" field.
func TriggeredValueIn(vs ...int64) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldTriggeredValue, vs...))
}

// TriggeredValueNotIn applies the NotIn predicate on the "triggered_value" field.
func TriggeredValueNotIn(vs ...int64) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldTriggeredValue, vs...))
}

// TriggeredValueGT applies the GT predicate on the "triggered_value" field.
func TriggeredValueGT(v int64) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGT(FieldTriggeredValue, v))
}

// TriggeredValueGTE applies the GTE predicate on the "triggered_value" field.
func TriggeredValueGTE(v int64) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGTE(FieldTriggeredValue, v))
}

// TriggeredValueLT applies the LT predicate on the "triggered_value" field.
func TriggeredValueLT(v int64) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLT(FieldTriggeredValue, v))
}

// TriggeredValueLTE applies the LTE predicate on the "triggered_value" field.
func TriggeredValueLTE(v int64) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLTE(FieldTriggeredValue, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldContainsFold(FieldMessage, v))
}

// IsResolvedEQ applies the EQ predicate on the "is_resolved" field.
func IsResolvedEQ(v bool) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldIsResolved, v))
}

// IsResolvedNEQ applies the NEQ predicate on the "is_resolved" field.
func IsResolvedNEQ(v bool) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldIsResolved, v))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotNull(FieldResolvedAt))
}

// ResolvedByEQ applies the EQ predicate on the "resolved_by" field.
func ResolvedByEQ(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldEQ(FieldResolvedBy, v))
}

// ResolvedByNEQ applies the NEQ predicate on the "resolved_by" field.
func ResolvedByNEQ(v uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNEQ(FieldResolvedBy, v))
}

// ResolvedByIn applies the In predicate on the "resolved_by" field.
func ResolvedByIn(vs ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIn(FieldResolvedBy, vs...))
}

// ResolvedByNotIn applies the NotIn predicate on the "resolved_by" field.
func ResolvedByNotIn(vs ...uuid.UUID) predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotIn(FieldResolvedBy, vs...))
}

// ResolvedByIsNil applies the IsNil predicate on the "resolved_by" field.
func ResolvedByIsNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldIsNull(FieldResolvedBy))
}

// ResolvedByNotNil applies the NotNil predicate on the "resolved_by" field.
func ResolvedByNotNil() predicate.AlertRecord {
	return predicate.AlertRecord(sql.FieldNotNull(FieldResolvedBy))
}

// HasRule applies the HasEdge predicate on the "rule" edge.
func HasRule() predicate.AlertRecord {
	return predicate.AlertRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RuleTable, RuleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRuleWith applies the HasEdge predicate on the "rule" edge with a given conditions (other predicates).
func HasRuleWith(preds ...predicate.AlertRule) predicate.AlertRecord {
	return predicate.AlertRecord(func(s *sql.Selector) {
		step := newRuleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AlertRecord {
	return predicate.AlertRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AlertRecord {
	return predicate.AlertRecord(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasToken applies the HasEdge predicate on the "token" edge.
func HasToken() predicate.AlertRecord {
	return predicate.AlertRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TokenTable, TokenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTokenWith applies the HasEdge predicate on the "token" edge with a given conditions (other predicates).
func HasTokenWith(preds ...predicate.UserToken) predicate.AlertRecord {
	return predicate.AlertRecord(func(s *sql.Selector) {
		step := newTokenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AlertRecord {
	return predicate.AlertRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AlertRecord {
	return predicate.AlertRecord(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResolver applies the HasEdge predicate on the "resolver" edge.
func HasResolver() predicate.AlertRecord {
	return predicate.AlertRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ResolverTable, ResolverColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResolverWith applies the HasEdge predicate on the "resolver" edge with a given conditions (other predicates).
func HasResolverWith(preds ...predicate.AdminUser) predicate.AlertRecord {
	return predicate.AlertRecord(func(s *sql.Selector) {
		step := newResolverStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AlertRecord) predicate.AlertRecord {
	return predicate.AlertRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AlertRecord) predicate.AlertRecord {
	return predicate.AlertRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AlertRecord) predicate.AlertRecord {
	return predicate.AlertRecord(sql.NotPredicates(p))
}
