// Code generated by ent, DO NOT EDIT.

package balancerecord

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the balancerecord type in the database.
	Label = "balance_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCallLogID holds the string denoting the call_log_id field in the database.
	FieldCallLogID = "call_log_id"
	// FieldRelatedOrderID holds the string denoting the related_order_id field in the database.
	FieldRelatedOrderID = "related_order_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldBalanceAfter holds the string denoting the balance_after field in the database.
	FieldBalanceAfter = "balance_after"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeCallLog holds the string denoting the call_log edge name in mutations.
	EdgeCallLog = "call_log"
	// EdgeRelatedOrder holds the string denoting the related_order edge name in mutations.
	EdgeRelatedOrder = "related_order"
	// Table holds the table name of the balancerecord in the database.
	Table = "balance_records"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "balance_records"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// CallLogTable is the table that holds the call_log relation/edge.
	CallLogTable = "balance_records"
	// CallLogInverseTable is the table name for the CallLog entity.
	// It exists in this package in order to avoid circular dependency with the "calllog" package.
	CallLogInverseTable = "call_logs"
	// CallLogColumn is the table column denoting the call_log relation/edge.
	CallLogColumn = "call_log_id"
	// RelatedOrderTable is the table that holds the related_order relation/edge.
	RelatedOrderTable = "balance_records"
	// RelatedOrderInverseTable is the table name for the RechargeOrder entity.
	// It exists in this package in order to avoid circular dependency with the "rechargeorder" package.
	RelatedOrderInverseTable = "recharge_orders"
	// RelatedOrderColumn is the table column denoting the related_order relation/edge.
	RelatedOrderColumn = "related_order_id"
)

// Columns holds all SQL columns for balancerecord fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldCallLogID,
	FieldRelatedOrderID,
	FieldType,
	FieldAmount,
	FieldBalanceAfter,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultBalanceAfter holds the default value on creation for the "balance_after" field.
	DefaultBalanceAfter int64
	// RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	RemarkValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeRecharge    Type = "recharge"
	TypeConsume     Type = "consume"
	TypeRefund      Type = "refund"
	TypeAdminAdjust Type = "admin_adjust"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeRecharge, TypeConsume, TypeRefund, TypeAdminAdjust:
		return nil
	default:
		return fmt.Errorf("balancerecord: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the BalanceRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCallLogID orders the results by the call_log_id field.
func ByCallLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallLogID, opts...).ToFunc()
}

// ByRelatedOrderID orders the results by the related_order_id field.
func ByRelatedOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedOrderID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByBalanceAfter orders the results by the balance_after field.
func ByBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfter, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByCallLogField orders the results by call_log field.
func ByCallLogField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCallLogStep(), sql.OrderByField(field, opts...))
	}
}

// ByRelatedOrderField orders the results by related_order field.
func ByRelatedOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRelatedOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
func newCallLogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CallLogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CallLogTable, CallLogColumn),
	)
}
func newRelatedOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RelatedOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RelatedOrderTable, RelatedOrderColumn),
	)
}
